// Generated by wxt
export {}
declare global {
  const ClassificationResult: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/storage').ClassificationResult
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const applyLocalRules: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/classifier').applyLocalRules
  const browser: typeof import('wxt/browser').browser
  const byokKeysStore: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/storage').byokKeysStore
  const classifyContent: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/classifier').classifyContent
  const classifyWithBYOK: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/classifier').classifyWithBYOK
  const classifyWithHosted: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/classifier').classifyWithHosted
  const clearDecisionCache: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/storage').clearDecisionCache
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const decisionCache: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/storage').decisionCache
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const getCachedResult: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/storage').getCachedResult
  const incrementFilteredCount: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/storage').incrementFilteredCount
  const initializeStores: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/storage').initializeStores
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const resetStats: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/storage').resetStats
  const setCachedResult: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/storage').setCachedResult
  const settingsStore: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/storage').settingsStore
  const statsStore: typeof import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/storage').statsStore
  const storage: typeof import('wxt/utils/storage').storage
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { ClassifierOptions } from '/home/dracon/Dev/extensions/calmweb/apps/extension/utils/classifier'
  import('/home/dracon/Dev/extensions/calmweb/apps/extension/utils/classifier')
}
