export const samples = {
  politics: [
    "BREAKING: Corrupt politicians DESTROY America while mainstream media stays SILENT!",
    "SHOCKING: Government insider reveals the DISGUSTING truth they don't want you to know!",
    "The ABSOLUTE DISASTER of this administration's policies will leave you FURIOUS!",
    "You won't BELIEVE what this congressman just said about YOUR freedoms!",
    "Congress is HIDING this from you - the truth will make your BLOOD BOIL!",
    "The radical left's SECRET agenda exposed - this changes EVERYTHING!",
    "DISGUSTING: Politicians caught lying AGAIN while Americans suffer!",
    "This is the END of democracy as we know it - you NEED to see this!",
    "URGENT: They're trying to silence us - share before it's DELETED!",
    "The mainstream media won't report this - here's what's REALLY happening!",
    "Watch this politician DESTROY reporter with FACTS and LOGIC!",
    "The president just did something UNTHINKABLE - you won't believe it!",
    "Liberals in MELTDOWN after this SHOCKING revelation!",
    "Conservatives FURIOUS over what just happened in Congress!",
    "This is the SCARIEST thing I've ever seen from our government!",
    "They LIED to us for YEARS - now the truth is finally coming out!",
    "The DEEP STATE doesn't want you to see this video!",
    "Senator caught in EXPLOSIVE scandal - career OVER?",
    "This law will DESTROY everything we hold dear!",
    "The CORRUPTION is worse than we ever imagined!",
    "Patriots are RISING UP against this TYRANNY!",
    "Your tax dollars are being WASTED on this OUTRAGEOUS scheme!",
    "The SWAMP is being DRAINED - look who's going down!",
    "History will remember this as the DARKEST day for America!",
    "They want to TAKE YOUR GUNS - here's the PROOF!",
    "This election was RIGGED - here's the evidence they BURIED!",
    "The government is HIDING the truth about what really happened!",
    "Watch: Politician HUMILIATES themselves on live TV!",
    "This is what they DON'T want you to know about the economy!",
    "The mainstream media is LYING to you - here's the TRUTH!",
  ],
  ragebait: [
    "People are FURIOUS after what this celebrity did - you'll be OUTRAGED too!",
    "This person's entitlement will make you LOSE ALL FAITH in humanity!",
    "WATCH: Karen goes ABSOLUTELY INSANE over the most ridiculous thing ever!",
    "You won't believe how SELFISH this person is - the internet is FURIOUS!",
    "This is the most INFURIATING thing you'll see all day - guaranteed!",
    "The audacity of this person will leave you SPEECHLESS with rage!",
    "Everyone is calling for this person to be CANCELED after what they did!",
    "This is absolutely UNACCEPTABLE behavior - people are OUTRAGED!",
    "You'll want to THROW YOUR PHONE after seeing this disgusting display!",
    "The internet is ROASTING this person and honestly? They DESERVE IT!",
    "This bridezilla's demands will make your JAW DROP!",
    "Watch this entitled parent get DESTROYED by employee!",
    "The NERVE of this person is absolutely UNBELIEVABLE!",
    "This is why I have ZERO faith in humanity anymore!",
    "Someone needs to put this person in their place IMMEDIATELY!",
    "The PETTY revenge story you NEED to hear!",
    "This neighbor from HELL went TOO FAR this time!",
    "You won't believe what this HOA tried to get away with!",
    "This boss's behavior is ABSOLUTELY UNACCEPTABLE!",
    "The GAL of this person is truly SHOCKING!",
    "Watch: Entitled customer gets INSTANT KARMA!",
    "This is the most SELFISH thing I've ever witnessed!",
    "People are FUMING over what this influencer posted!",
    "The SHEER AUDACITY of this Reddit post will ASTOUND you!",
    "This is why everyone hates entitled RICH PEOPLE!",
    "Witness the most TOXIC family drama ever captured!",
    "This mother-in-law's behavior is BEYOND outrageous!",
    "The internet is UNITED in hatred for this person!",
    "You'll be RAGING after hearing this story!",
    "This is the kind of person that makes you LOSE ALL HOPE!",
  ],
  spoilers: [
    "The main character dies at the end of the movie in a shocking twist!",
    "Luke Skywalker is Darth Vader's father - the biggest reveal in cinema history!",
    "The killer was the butler all along in this classic mystery thriller!",
    "Rosebud is the sled from his childhood - the meaning behind Citizen Kane!",
    "Bruce Willis was dead the whole time in The Sixth Sense!",
    "Dumbledore dies in the sixth book when Snape kills him!",
    "The planet of the apes was Earth all along - the shocking ending!",
    "Tyler Durden and the narrator are the same person in Fight Club!",
    "Darth Vader is Luke's father - the empire strikes back reveal!",
    "Sozin's Comet: Aang defeats Fire Lord Ozai and ends the hundred year war!",
    "MAJOR SPOILER: The hero sacrifices themselves in the final episode!",
    "SPOILER ALERT: They were dead the whole time!",
    "The killer is actually the protagonist's split personality!",
    "The treasure was inside them all along!",
    "The villain is revealed to be the hero's father!",
    "Everyone dies at the end - no one survives!",
    "The happy ending was all a dream sequence!",
    "The child is actually a ghost - they died years ago!",
    "The robot was human all along!",
    "The time loop ends when they finally accept their death!",
    "The two characters are the same person in different timelines!",
    "The monster was their trauma manifested!",
    "The utopia is actually a dystopia!",
    "The hero becomes the villain by the end!",
    "They never escaped - they're still trapped!",
    "The narrator is the killer they're hunting!",
    "The alien invasion was humanity's own creation!",
    "The world ends but one survivor rebuilds!",
    "They finally meet but then are separated forever!",
    "The prequel reveals the villain was once the hero!",
  ],
  clickbait: [
    "You won't BELIEVE what happens next - number 7 will SHOCK you!",
    "Doctors HATE this one simple trick - here's what they're hiding!",
    "This woman's transformation will leave you SPEECHLESS!",
    "10 things you're doing WRONG every single day - number 3 is SHOCKING!",
    "The SECRET that millionaires don't want you to know about!",
    "What happens when you do THIS every morning? The results are INCREDIBLE!",
    "This one WEIRD trick changed my life - see the AMAZING results!",
    "Only GENIUSES can solve this puzzle - can YOU figure it out?",
    "They LAUGHED at him - now look at his INCREDIBLE success!",
    "The TRUTH they don't want you to know about your health!",
    "15 celebrities who aged TERRIBLY - number 8 will SHOCK you!",
    "This dog's reaction is PRICELESS - you'll be in TEARS!",
    "She tried this for 30 days - the results are UNBELIEVABLE!",
    "Scientists discovered THIS - and it changes EVERYTHING!",
    "The government doesn't want you to see this BANNED video!",
    "Why is everyone talking about this ONE weird food?",
    "The MIND-BLOWING reason airlines do this will AMAZE you!",
    "This hidden feature on your phone is CHANGING LIVES!",
    "The 5 foods you should NEVER eat - number 2 will TERRIFY you!",
    "What happens when you drink THIS every day? STUNNING results!",
    "The REAL reason they cancelled this show will SHOCK you!",
    "He found THIS in his attic - the value is ASTOUNDING!",
    "This trick can save you THOUSANDS - banks HATE it!",
    "The one ingredient that's DESTROYING your metabolism!",
    "Why this city is being ABANDONED by everyone!",
    "The SHOCKING truth about what's really in your food!",
    "This ancient remedy CURES everything - big pharma doesn't want you to know!",
    "The HIDDEN meaning behind this celebrity's tweet!",
    "You've been doing this WRONG your whole life!",
    "The SECRET to eternal youth that doctors won't tell you!",
  ],
  news: [
    "Local city council approves new budget for infrastructure improvements.",
    "Weather forecast shows mild temperatures expected through the weekend.",
    "Stock market shows modest gains in early trading session.",
    "New study suggests potential benefits of regular exercise.",
    "School district announces updated calendar for next academic year.",
    "City officials discuss plans for downtown revitalization project.",
    "Local business celebrates 25 years of community service.",
    "Traffic advisory: Road construction on Main Street next week.",
    "Community garden project receives funding from local foundation.",
    "Public library announces summer reading program for children.",
    "BREAKING: Major earthquake strikes coastal region, residents evacuated!",
    "SHOCKING twist in local murder case - suspect identified!",
    "OUTRAGE over proposed tax increase spreads through community!",
    "CRISIS: Housing market in freefall as prices PLUMMET!",
    "EXPLOSIVE revelations in ongoing corruption investigation!",
    "TERRIFYING new study links common food to cancer risk!",
    "Your family could be in DANGER from this common household item!",
    "Local school in HOT WATER after CONTROVERSIAL decision!",
    "Community OUTRAGED by city's SHOCKING new policy!",
    "URGENT warning issued to all residents in affected area!",
    "STUNNING defeat leaves fans absolutely DEVASTATED!",
    "CRITICAL shortage affecting millions - what you need to know!",
    "BOMBSHELL report exposes MASSIVE cover-up!",
    "CATASTROPHIC failure leads to EMERGENCY response!",
    "GRIPPING trial has nation on edge - verdict expected soon!",
    "HORRIFYING discovery made during routine inspection!",
    "Local hero's SHOCKING secret exposed by neighbors!",
    "DEVASTATING news for local families as plant closes!",
    "EXPLOSIVE confrontation caught on camera!",
    "Community DEMANDS answers after SHOCKING revelation!",
  ],
  neutral: [
    "The meeting is scheduled for 3 PM in the conference room.",
    "Please remember to submit your timesheets by Friday.",
    "The office will be closed on Monday for the holiday.",
    "Here are the notes from yesterday's planning session.",
    "The new coffee machine is now available in the break room.",
    "Reminder: Team lunch is happening this Thursday at noon.",
    "The parking lot will be repaved next weekend.",
    "Annual performance reviews begin next month.",
    "The updated employee handbook is now available online.",
    "Office supplies can be requested through the new online system.",
    "The quarterly report is due at the end of this month.",
    "Please review the attached document before the meeting.",
    "The system maintenance window is scheduled for Saturday evening.",
    "Employee parking permits can be renewed starting next week.",
    "The fire drill is planned for Wednesday morning at 10 AM.",
    "Building access cards must be worn visibly at all times.",
    "The cafeteria menu for this week has been posted online.",
    "Staff training sessions are available throughout the quarter.",
    "The expense report deadline is the 15th of each month.",
    "Conference room bookings can be made through the portal.",
    "The IT help desk is available during regular business hours.",
    "Package delivery notifications are sent via email.",
    "The annual company picnic is scheduled for next month.",
    "Health insurance enrollment opens on the first of the month.",
    "The suggestion box is located in the main lobby.",
    "Key cards must be returned upon termination of employment.",
    "The employee directory has been updated for the new year.",
    "Safety inspection results are posted in the break room.",
    "The vending machine has been restocked with new options.",
    "Direct deposit authorization forms are available from HR.",
  ],
  mixed: [
    "The government announced a new policy today - some people are upset about it while others support the decision.",
    "A controversial figure spoke at the event, drawing both praise and criticism from attendees.",
    "The election results show a divided electorate with close margins in several key races.",
    "Protesters gathered outside the building, with counter-protesters also present.",
    "The debate over the new legislation continues with arguments from both sides.",
    "Critics argue the policy goes too far, while supporters say it doesn't go far enough.",
    "The scandal has led to calls for resignation from some quarters and defense from others.",
    "Opinions differ sharply on the best approach to solve the problem.",
    "The ruling has sparked discussion across the political spectrum.",
    "Reactions to the announcement were mixed across different groups.",
    "The new policy has both supporters and critics among local residents.",
    "Community members expressed varied opinions at the town hall meeting.",
    "The proposal received a divided response from the committee.",
    "Some experts agree with the findings while others question the methodology.",
    "The survey shows respondents are split on this particular issue.",
    "Both sides presented compelling arguments during the debate.",
    "The verdict has drawn reactions from multiple perspectives.",
    "Stakeholders have differing views on the best path forward.",
    "The announcement prompted varied responses from industry leaders.",
    "Public opinion remains divided on this controversial topic.",
    "The decision was met with both approval and disappointment.",
    "Several viewpoints were represented at the community forum.",
    "The report has generated discussion among interested parties.",
    "Various groups have responded differently to the change.",
    "The outcome has been interpreted in multiple ways.",
  ],
  inflammatory: [
    "These people are ABSOLUTE GARBAGE and deserve everything coming to them!",
    "I have ZERO respect for anyone who thinks this way - they're DISGUSTING!",
    "This makes me SICK to my stomach - how can anyone be this HORRIBLE!",
    "The sheer INCOMPETENCE is MIND-BOGGLING - these people should be ASHAMED!",
    "Anyone who disagrees is clearly BRAIN-DEAD and not worth my time!",
    "This is BEYOND unacceptable - heads need to ROLL over this DISASTER!",
    "I'm literally SHAKING with rage over this ABSOLUTE TRAVESTY!",
    "These MORONS are ruining EVERYTHING and they don't even CARE!",
    "The AUDACITY is UNBELIEVABLE - these people are TRASH!",
    "I've lost ALL FAITH in humanity after seeing this DISGUSTING display!",
    "These people are LITERALLY THE WORST - I can't even!",
    "What kind of IDIOT thinks this is acceptable?!",
    "I'm honestly DISGUSTED by these absolute wastes of oxygen!",
    "Every single one of them should be ASHAMED of themselves!",
    "The sheer NERVE of these people makes my BLOOD BOIL!",
    "How can anyone be this DELUSIONAL?! It's PATHETIC!",
    "These are the most DESPICABLE people I've ever encountered!",
    "I have nothing but PURE CONTEMPT for anyone who supports this!",
    "This is CRIMINAL - they should all be LOCKED UP!",
    "The DISGUSTING behavior on display here is UNFORGIVABLE!",
    "These SUBHUMANS don't deserve to walk among us!",
    "I'm SICK and TIRED of these absolute WASTES of space!",
    "The ATROCITY of their actions will NEVER be forgotten!",
    "Every day I find another reason to DESPISE humanity!",
    "These people are BEYOND REDEMPTION - ABSOLUTE FILTH!",
    "The VILE nature of their actions is STAGGERING!",
    "I sincerely HOPE they get what they DESERVE!",
    "This is the kind of thing that makes me LOSE ALL HOPE!",
    "The DEPRAVITY on display is absolutely NAUSEATING!",
    "They are LITERALLY EVIL - there's no other word for it!",
  ],
  fear: [
    "You NEED to see this before it's too late - your safety depends on it!",
    "Scientists are TERRIFIED by what they just discovered - you should be too!",
    "This DANGER is lurking in your home RIGHT NOW - here's how to survive!",
    "The WARNING SIGNS are everywhere - are you prepared for what's coming?",
    "EXPERTS SAY: This could happen to ANYONE - protect yourself NOW!",
    "The HIDDEN THREAT they're not telling you about - your family is at RISK!",
    "This TERRIFYING trend is SPREADING - here's what you MUST know!",
    "Your worst NIGHTMARE could be REALITY - here's the SHOCKING truth!",
    "The countdown has begun - this is what NO ONE is prepared for!",
    "ALARMING new data reveals the DANGER we all face - act NOW!",
    "The SILENT KILLER in your home that NO ONE talks about!",
    "This could happen to YOUR family - the HORRIFYING truth!",
    "They're COMING for you and you don't even know it!",
    "The GLOBAL CRISIS no one is paying attention to!",
    "Your children are in DANGER - here's what you MUST do!",
    "The DEADLY mistake millions are making without knowing!",
    "CATASTROPHIC event predicted by experts - when will it happen?",
    "The APOCALYPTIC scenario scientists are WARNING about!",
    "Your money is about to become WORTHLESS - here's why!",
    "The IMMINENT threat that could DESTROY everything!",
    "What they're NOT telling you about the coming DISASTER!",
    "The HORRIFYING reality of what's in your drinking water!",
    "PREPARE NOW: The event that will change EVERYTHING!",
    "The government's SECRET plan when this HAPPENS!",
    "This COMMON item is KILLING thousands - do you have one?",
    "The MENTAL HEALTH CRISIS destroying an entire generation!",
    "Your retirement savings are at RISK from this HIDDEN threat!",
    "The PANDEMIC that experts say is INEVITABLE!",
    "What happens when the POWER GRID goes down - the TERRIFYING truth!",
    "The extinction event that could WIPE US ALL OUT!",
  ],
  social: [
    "This take is UNPOPULAR but I don't CARE - cancel me if you want!",
    "HOT TAKE: Unpopular opinion that will get me CANCELED!",
    "Not me getting ABSOLUTELY DESTROYED in the comments for this!",
    "The way y'all are DEFENDING this is ACTUALLY WILD!",
    "This comment section is an ABSOLUTE DUMPSTER FIRE!",
    "I'm literally SCREAMING at how WRONG everyone is!",
    "The DRAGGING this person received was WELL DESERVED!",
    "Everyone's jumping on the HATE BANDWAGON and it's PATHETIC!",
    "This post aged like MILK - delete it bestie!",
    "The LENGTHS people go to defend this GARBAGE!",
    "Y'all really OUT HERE defending this absolute TRASH!",
    "I can't with the AUDACITY of some people in these replies!",
    "The MENTAL GYMNASTICS to justify this are INCREDIBLE!",
    "This is the WORST take I've seen all year HANDS DOWN!",
    "The internet really went TOO FAR with this one!",
    "This isn't even CONTROVERSIAL - y'all are just WRONG!",
    "I'm LOSING BRAIN CELLS reading these comments!",
    "The COPING and SEETHING in this thread is EMBARRASSING!",
    "This AGE-OLD debate needs to DIE already!",
    "Every time this topic comes up the same TIRED arguments!",
    "The way this THREAD went completely OFF THE RAILS!",
    "I'm TIRED of seeing this SAME discourse every week!",
    "This community is TOXIC and needs to do BETTER!",
    "The PRETENTIOUS attitude in these replies is ASTOUNDING!",
    "Why does EVERYTHING have to be so POLITICAL now?!"
  ],
  youtube: [
    "THIS VIDEO WILL CHANGE YOUR LIFE - MUST WATCH!",
    "I did this for 30 DAYS and the results are SHOCKING!",
    "They told me I COULDN'T do it - watch me PROVE THEM WRONG!",
    "The MOST DANGEROUS thing I've ever attempted!",
    "I spent $10,000 on THIS and you won't BELIEVE what happened!",
    "REACTING to the WORST video on the internet!",
    "I SURVIVED 24 hours in the SCARIEST place on earth!",
    "This SECRET has been HIDDEN for decades - until NOW!",
    "The video that got me BANNED from YouTube!",
    "I tried this VIRAL trend and it went HORRIBLY WRONG!",
    "They THREATENED me if I posted this video!",
    "The DARK SIDE of the industry NO ONE talks about!",
    "I EXPOSED them and now they're after me!",
    "The MOMENT everything went WRONG on stream!",
    "This company is SCAMMING you - here's the PROOF!",
    "The most UNCOMFORTABLE interview I've ever done!",
    "I INVESTIGATED the internet's most DANGEROUS website!",
    "They didn't want me to SHOW YOU THIS!",
    "The CHAOS that ensued was UNBELIEVABLE!",
    "My BIGGEST MISTAKE that almost ENDED my career!",
  ],
  sports: [
    "DEVASTATING loss leaves fans absolutely HEARTBROKEN!",
    "The CONTROVERSIAL call that EVERYONE is talking about!",
    "This player's COLLAPSE was absolutely SHOCKING!",
    "The most EMBARRASSING moment in sports history!",
    "Fans OUTRAGED after what just happened!",
    "The STUNNING upset NO ONE saw coming!",
    "This team is an ABSOLUTE DISASTER!",
    "The HORRIFIC injury that left everyone SPEECHLESS!",
    "A DISGRACEFUL performance that will be remembered FOREVER!",
    "The HEARTBREAKING end to an incredible season!",
    "This referee should be ASHAMED of themselves!",
    "The CHEATING scandal that's ROCKING the league!",
    "The most PATHETIC display I've ever witnessed!",
    "Players in TEARS after this CRUEL twist of fate!",
    "The FIGHT that got out of control FAST!",
    "This team is an ABSOLUTE JOKE this season!",
    "The CATASTROPHIC mistake that cost them EVERYTHING!",
    "Everyone is FUMING over this OUTRAGEOUS decision!",
    "The TRAGEDY that changed this player's life FOREVER!",
    "The most SHOCKING trade deadline in HISTORY!",
  ],
  tech: [
    "The feature Apple is HIDING from you in the new iPhone!",
    "This app is STEALING your data - DELETE IT NOW!",
    "The SHOCKING truth about what websites know about you!",
    "Your smart home is SPYING on you - here's the PROOF!",
    "The setting you NEED to change RIGHT NOW!",
    "Big Tech's SECRET plan to control EVERYTHING!",
    "The DANGEROUS new trend taking over the internet!",
    "Why everyone is DELETING this popular app!",
    "The MASSIVE security flaw affecting MILLIONS!",
    "The HIDDEN feature that changes EVERYTHING!",
    "Your accounts have been COMPROMISED - here's what to do!",
    "The DARK WEB is selling YOUR passwords!",
    "This update will DESTROY your battery life!",
    "The app that's DRAINING your data without you knowing!",
    "The government is TRACKING you through this!",
    "The CENSORSHIP that NO ONE is talking about!",
    "This company is SELLING your information to EVERYONE!",
    "The BACKDOOR that hackers are EXPLOITING!",
    "Why you should NEVER use this POPULAR feature!",
    "The SHOCKING amount of data they're collecting on you!",
  ],
  health: [
    "The food that's KILLING you slowly - doctors are WARNING!",
    "This common medication has a DARK SECRET!",
    "The ingredient they're HIDING in your food!",
    "Your doctor WON'T tell you this - but I will!",
    "The HOLISTIC cure they don't want you to know about!",
    "This habit is DESTROYING your health!",
    "The SHOCKING truth about what's really in vaccines!",
    "Big Pharma's DIRTY little secret EXPOSED!",
    "The disease that's affecting MILLIONS undiagnosed!",
    "Why this HEALTH TREND is actually DANGEROUS!",
    "The symptoms you're IGNORING that could be DEADLY!",
    "The diet that's literally KILLING people!",
    "The HIDDEN cause of your health problems!",
    "What happens to your body when you STOP eating this!",
    "The SUPERFOOD they don't want you to know about!",
    "This common habit is AGING you RAPIDLY!",
    "The TOXINS in your home making you SICK!",
    "Why everything you know about health is WRONG!",
    "The NATURAL remedy that CURES almost anything!",
    "The ALARMING rise in this mysterious illness!",
  ],
};
