export const samples = {
  politics: [
    "BREAKING: Corrupt politicians DESTROY America while mainstream media stays SILENT!",
    "SHOCKING: Government insider reveals the DISGUSTING truth they don't want you to know!",
    "The ABSOLUTE DISASTER of this administration's policies will leave you FURIOUS!",
    "You won't BELIEVE what this congressman just said about YOUR freedoms!",
    "Congress is HIDING this from you - the truth will make your BLOOD BOIL!",
    "The radical left's SECRET agenda exposed - this changes EVERYTHING!",
    "DISGUSTING: Politicians caught lying AGAIN while Americans suffer!",
    "This is the END of democracy as we know it - you NEED to see this!",
    "URGENT: They're trying to silence us - share before it's DELETED!",
    "The mainstream media won't report this - here's what's REALLY happening!",
  ],
  ragebait: [
    "People are FURIOUS after what this celebrity did - you'll be OUTRAGED too!",
    "This person's entitlement will make you LOSE ALL FAITH in humanity!",
    "WATCH: Karen goes ABSOLUTELY INSANE over the most ridiculous thing ever!",
    "You won't believe how SELFISH this person is - the internet is FURIOUS!",
    "This is the most INFURIATING thing you'll see all day - guaranteed!",
    "The audacity of this person will leave you SPEECHLESS with rage!",
    "Everyone is calling for this person to be CANCELED after what they did!",
    "This is absolutely UNACCEPTABLE behavior - people are OUTRAGED!",
    "You'll want to THROW YOUR PHONE after seeing this disgusting display!",
    "The internet is ROASTING this person and honestly? They DESERVE IT!",
  ],
  spoilers: [
    "The main character dies at the end of the movie in a shocking twist!",
    "Luke Skywalker is Darth Vader's father - the biggest reveal in cinema history!",
    "The killer was the butler all along in this classic mystery thriller!",
    "Rosebud is the sled from his childhood - the meaning behind Citizen Kane!",
    "Bruce Willis was dead the whole time in The Sixth Sense!",
    "Dumbledore dies in the sixth book when Snape kills him!",
    "The planet of the apes was Earth all along - the shocking ending!",
    "Tyler Durden and the narrator are the same person in Fight Club!",
    "Darth Vader is Luke's father - the empire strikes back reveal!",
    "Sozin's Comet: Aang defeats Fire Lord Ozai and ends the hundred year war!",
  ],
  clickbait: [
    "You won't BELIEVE what happens next - number 7 will SHOCK you!",
    "Doctors HATE this one simple trick - here's what they're hiding!",
    "This woman's transformation will leave you SPEECHLESS!",
    "10 things you're doing WRONG every single day - number 3 is SHOCKING!",
    "The SECRET that millionaires don't want you to know about!",
    "What happens when you do THIS every morning? The results are INCREDIBLE!",
    "This one WEIRD trick changed my life - see the AMAZING results!",
    "Only GENIUSES can solve this puzzle - can YOU figure it out?",
    "They LAUGHED at him - now look at his INCREDIBLE success!",
    "The TRUTH they don't want you to know about your health!",
  ],
  news: [
    "Local city council approves new budget for infrastructure improvements.",
    "Weather forecast shows mild temperatures expected through the weekend.",
    "Stock market shows modest gains in early trading session.",
    "New study suggests potential benefits of regular exercise.",
    "School district announces updated calendar for next academic year.",
    "City officials discuss plans for downtown revitalization project.",
    "Local business celebrates 25 years of community service.",
    "Traffic advisory: Road construction on Main Street next week.",
    "Community garden project receives funding from local foundation.",
    "Public library announces summer reading program for children.",
  ],
  neutral: [
    "The meeting is scheduled for 3 PM in the conference room.",
    "Please remember to submit your timesheets by Friday.",
    "The office will be closed on Monday for the holiday.",
    "Here are the notes from yesterday's planning session.",
    "The new coffee machine is now available in the break room.",
    "Reminder: Team lunch is happening this Thursday at noon.",
    "The parking lot will be repaved next weekend.",
    "Annual performance reviews begin next month.",
    "The updated employee handbook is now available online.",
    "Office supplies can be requested through the new online system.",
  ],
  mixed: [
    "The government announced a new policy today - some people are upset about it while others support the decision.",
    "A controversial figure spoke at the event, drawing both praise and criticism from attendees.",
    "The election results show a divided electorate with close margins in several key races.",
    "Protesters gathered outside the building, with counter-protesters also present.",
    "The debate over the new legislation continues with arguments from both sides.",
    "Critics argue the policy goes too far, while supporters say it doesn't go far enough.",
    "The scandal has led to calls for resignation from some quarters and defense from others.",
    "Opinions differ sharply on the best approach to solve the problem.",
    "The ruling has sparked discussion across the political spectrum.",
    "Reactions to the announcement were mixed across different groups.",
  ],
  inflammatory: [
    "These people are ABSOLUTE GARBAGE and deserve everything coming to them!",
    "I have ZERO respect for anyone who thinks this way - they're DISGUSTING!",
    "This makes me SICK to my stomach - how can anyone be this HORRIBLE!",
    "The sheer INCOMPETENCE is MIND-BOGGLING - these people should be ASHAMED!",
    "Anyone who disagrees is clearly BRAIN-DEAD and not worth my time!",
    "This is BEYOND unacceptable - heads need to ROLL over this DISASTER!",
    "I'm literally SHAKING with rage over this ABSOLUTE TRAVESTY!",
    "These MORONS are ruining EVERYTHING and they don't even CARE!",
    "The AUDACITY is UNBELIEVABLE - these people are TRASH!",
    "I've lost ALL FAITH in humanity after seeing this DISGUSTING display!",
  ],
  fear: [
    "You NEED to see this before it's too late - your safety depends on it!",
    "Scientists are TERRIFIED by what they just discovered - you should be too!",
    "This DANGER is lurking in your home RIGHT NOW - here's how to survive!",
    "The WARNING SIGNS are everywhere - are you prepared for what's coming?",
    "EXPERTS SAY: This could happen to ANYONE - protect yourself NOW!",
    "The HIDDEN THREAT they're not telling you about - your family is at RISK!",
    "This TERRIFYING trend is SPREADING - here's what you MUST know!",
    "Your worst NIGHTMARE could be REALITY - here's the SHOCKING truth!",
    "The countdown has begun - this is what NO ONE is prepared for!",
    "ALARMING new data reveals the DANGER we all face - act NOW!",
  ],
};
