import type { RewriteMode, RewriteResult, TextChange } from './rewriter';

interface NeutralizationRule {
  pattern: RegExp;
  replacement: string;
  strength: 'light' | 'medium' | 'strict';
  preserveCapitalization?: boolean;
}

const NEUTRALIZATION_RULES: NeutralizationRule[] = [
  { pattern: /\b(shocking|jaw-dropping|mind-blowing|earth-shattering|game-changing)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(you won't believe)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(you won't BELIEVE)\b/g, replacement: '', strength: 'light' },
  { pattern: /\b(this will make you (angry|furious|mad|rage))\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(can't believe)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(will make your blood boil)\b/gi, replacement: 'may concern you', strength: 'medium' },
  { pattern: /\b(blood boil)\b/gi, replacement: 'concern', strength: 'medium' },
  { pattern: /\boutrage\b/gi, replacement: 'discussion', strength: 'medium' },
  { pattern: /\boutraged\b/gi, replacement: 'concerned', strength: 'medium' },
  { pattern: /\bfurious\b/gi, replacement: 'concerned', strength: 'medium' },
  { pattern: /\b(furiously|fury)\b/gi, replacement: 'strongly', strength: 'medium' },
  { pattern: /\b(people are (angry|furious|outraged))\b/gi, replacement: 'people are discussing', strength: 'medium' },
  { pattern: /\b(backlash( erupts| grows| over)?)\b/gi, replacement: 'response', strength: 'medium' },
  { pattern: /\b(sparks? outrage)\b/gi, replacement: 'prompts discussion', strength: 'medium' },
  { pattern: /\b(terrifying( new| truth| reality)?)\b/gi, replacement: 'concerning', strength: 'medium' },
  { pattern: /\b(TERRIFYING)\b/g, replacement: 'Concerning', strength: 'medium' },
  { pattern: /\b(terrified)\b/gi, replacement: 'concerned', strength: 'medium' },
  { pattern: /\b(disaster|catastrophe)\b/gi, replacement: 'situation', strength: 'strict' },
  { pattern: /\b(democrat|republican)\b/gi, replacement: 'politician', strength: 'strict' },
  { pattern: /\b(democrats|republicans)\b/gi, replacement: 'politicians', strength: 'strict' },
  { pattern: /\b(the (real|hidden|secret) truth)\b/gi, replacement: 'the facts', strength: 'medium' },
  { pattern: /\b(what (they|the media|experts) (won't|don't) tell you)\b/gi, replacement: 'what may not be widely known', strength: 'medium' },
  { pattern: /\b(breaking:)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(BREAKING:)\b/g, replacement: '', strength: 'light' },
  { pattern: /\b(breaking news[:\s]*)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(explosive|bombshell|stunning)\b/gi, replacement: 'significant', strength: 'light' },
  { pattern: /\b(one weird trick)\b/gi, replacement: 'a method', strength: 'light' },
  { pattern: /\b(doctors (hate|don't want you to know))\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(EXCLUSIVE[:\s]+(report|news|video|story|interview|photos|images))/gi, replacement: '', strength: 'light' },
  { pattern: /\b(leaked[:\s])/gi, replacement: 'reported:', strength: 'medium' },
  { pattern: /\b(they don't want you to know)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b([A-Z]+[\s]+DESTROY(ED|S|ING)?)\b/g, replacement: 'affects', strength: 'medium' },
  { pattern: /\b(GETS?\s+DESTROY(ED)?)\b/gi, replacement: 'is affected', strength: 'medium' },
  { pattern: /\b(DESTROY(ED|S)?\s+BY)\b/gi, replacement: 'affected by', strength: 'medium' },
  { pattern: /\b(destroy\s+(everything|everyone|all|completely|totally))\b/gi, replacement: 'affect', strength: 'medium' },
  { pattern: /\b(ABSOLUTE(LY)? (DISASTER|GARBAGE|TRASH|NIGHTMARE))\b/gi, replacement: 'significant issue', strength: 'medium' },
  { pattern: /\b(disgusting)\b/gi, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(DISGUSTING)\b/g, replacement: 'Problematic', strength: 'medium' },
  { pattern: /\b(infuriating)\b/gi, replacement: 'frustrating', strength: 'medium' },
  { pattern: /\b(INFURIATING)\b/g, replacement: 'Frustrating', strength: 'medium' },
  { pattern: /\b(outrageous)\b/gi, replacement: 'questionable', strength: 'medium' },
  { pattern: /\b(SHOCK(ing|ed|s)?)\b/g, replacement: 'Surprise', strength: 'light' },
  { pattern: /\b(shock(ing|ed|s)?)\b/gi, replacement: 'surprise', strength: 'light' },
  { pattern: /\b(BELIEVE)\b/g, replacement: 'consider', strength: 'light' },
  { pattern: /\b(UNACCEPTABLE)\b/g, replacement: 'Problematic', strength: 'medium' },
  { pattern: /\b(unacceptable)\b/g, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(MORON(S)?)\b/g, replacement: 'people', strength: 'medium' },
  { pattern: /\b(moron(s)?)\b/gi, replacement: 'people', strength: 'medium' },
  { pattern: /\b(IDIOT(S)?)\b/g, replacement: 'people', strength: 'medium' },
  { pattern: /\b(idiot(s)?)\b/gi, replacement: 'people', strength: 'medium' },
  { pattern: /\b(STUPID)\b/g, replacement: 'unwise', strength: 'medium' },
  { pattern: /\b(stupid)\b/gi, replacement: 'unwise', strength: 'medium' },
  { pattern: /\b(BRAIN[- ]DEAD)\b/gi, replacement: 'uninformed', strength: 'medium' },
  { pattern: /\b(brain[- ]dead)\b/gi, replacement: 'uninformed', strength: 'medium' },
  { pattern: /\b(TRASH)\b/g, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(trash)\b/gi, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(GARBAGE)\b/g, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(garbage)\b/gi, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(INSANE)\b/g, replacement: 'unusual', strength: 'medium' },
  { pattern: /\b(insane)\b/gi, replacement: 'unusual', strength: 'medium' },
  { pattern: /\b(SPEECHLESS)\b/g, replacement: 'surprised', strength: 'medium' },
  { pattern: /\b(speechless)\b/gi, replacement: 'surprised', strength: 'medium' },
  { pattern: /\b(FURIOUS)\b/g, replacement: 'Concerned', strength: 'medium' },
  { pattern: /\b(FURIOUSLY)\b/g, replacement: 'Strongly', strength: 'medium' },
  { pattern: /\b(OUTRAGED)\b/g, replacement: 'Concerned', strength: 'medium' },
  { pattern: /\b(OUTRAGEOUS)\b/g, replacement: 'Questionable', strength: 'medium' },
  { pattern: /\b(RAGE)\b/g, replacement: 'concern', strength: 'medium' },
  { pattern: /\b(RAGING)\b/g, replacement: 'concerned', strength: 'medium' },
  { pattern: /\b(HORRIBLE)\b/g, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(horrible)\b/gi, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(DISASTER)\b/g, replacement: 'Issue', strength: 'medium' },
  { pattern: /\b(ABSOLUTE)\b/g, replacement: 'significant', strength: 'medium' },
  { pattern: /\b(absolute)\b/g, replacement: 'significant', strength: 'medium' },
  { pattern: /\b(CORRUPT)\b/g, replacement: 'controversial', strength: 'medium' },
  { pattern: /\b(corrupt)\b/gi, replacement: 'controversial', strength: 'medium' },
  { pattern: /\b(SECRET)\b/g, replacement: 'undisclosed', strength: 'light' },
  { pattern: /\b(HIDING)\b/g, replacement: 'withholding', strength: 'light' },
  { pattern: /\b(hiding)\b/gi, replacement: 'withholding', strength: 'light' },
  { pattern: /\b(SILENT)\b/g, replacement: 'quiet', strength: 'light' },
  { pattern: /\b(SILENCE)\b/g, replacement: 'quiet', strength: 'light' },
  { pattern: /\b(EXPOSED)\b/g, replacement: 'revealed', strength: 'light' },
  { pattern: /\b(exposed)\b/gi, replacement: 'revealed', strength: 'light' },
  { pattern: /\b(EVERYTHING)\b/g, replacement: 'a lot', strength: 'light' },
  { pattern: /\b(INCREDIBLE)\b/g, replacement: 'notable', strength: 'light' },
  { pattern: /\b(incredible)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(AMAZING)\b/g, replacement: 'notable', strength: 'light' },
  { pattern: /\b(amazing)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(MUST (SEE|READ|WATCH))\b/g, replacement: 'may want to see', strength: 'light' },
  { pattern: /\b(NEED TO (SEE|READ|KNOW))\b/gi, replacement: 'may want to', strength: 'light' },
  { pattern: /\b(NEED TO)\b/g, replacement: 'may want to', strength: 'light' },
  { pattern: /\b(URGENT:?)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(act now)\b/gi, replacement: 'consider', strength: 'medium' },
  { pattern: /\b(before it's too late)\b/gi, replacement: '', strength: 'medium' },
  { pattern: /\b(will leave you (speechless|furious|angry|outraged))\b/gi, replacement: 'may interest you', strength: 'medium' },
  { pattern: /\b(make you (lose faith|sick|angry|furious))\b/gi, replacement: 'may concern you', strength: 'medium' },
  { pattern: /\b(ROASTING)\b/g, replacement: 'criticizing', strength: 'medium' },
  { pattern: /\b(CANCELED)\b/g, replacement: 'criticized', strength: 'medium' },
  { pattern: /\b(CANCELLING)\b/g, replacement: 'criticizing', strength: 'medium' },
  { pattern: /\b(DESERVE)\b/g, replacement: 'may face', strength: 'medium' },
  { pattern: /\b(DESPICABLE)\b/g, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(ATROCIOUS)\b/g, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(UNBELIEVABLE)\b/g, replacement: 'notable', strength: 'light' },
  { pattern: /\b(unbelievable)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(AUDACITY)\b/g, replacement: 'action', strength: 'medium' },
  { pattern: /\b(audacity)\b/gi, replacement: 'action', strength: 'medium' },
  { pattern: /\b(MIND-BOGGLING)\b/g, replacement: 'notable', strength: 'light' },
  { pattern: /\b(SICK)\b/g, replacement: 'concerned', strength: 'medium' },
  { pattern: /\b(SHAKING)\b/g, replacement: 'affected', strength: 'medium' },
  { pattern: /\b(TRAVESTY)\b/g, replacement: 'situation', strength: 'medium' },
  { pattern: /\b(travesty)\b/gi, replacement: 'situation', strength: 'medium' },
  { pattern: /\b(FAITH IN HUMANITY)\b/gi, replacement: 'confidence', strength: 'medium' },
  { pattern: /\b(ASHAMED)\b/g, replacement: 'should reconsider', strength: 'medium' },
  { pattern: /\b(should be ashamed)\b/gi, replacement: 'should reconsider', strength: 'medium' },
  { pattern: /\b(LOSE ALL FAITH)\b/gi, replacement: 'be concerned', strength: 'medium' },
  { pattern: /\b(LOSE FAITH)\b/gi, replacement: 'be concerned', strength: 'medium' },
  { pattern: /\b(RADICAL)\b/g, replacement: 'active', strength: 'medium' },
  { pattern: /\b(radical)\b/gi, replacement: 'active', strength: 'medium' },
  { pattern: /\b(END OF)\b/g, replacement: 'change in', strength: 'medium' },
  { pattern: /\b(DANGER)\b/g, replacement: 'issue', strength: 'medium' },
  { pattern: /\b(danger)\b/gi, replacement: 'issue', strength: 'medium' },
  { pattern: /\b(DANGEROUS)\b/g, replacement: 'risky', strength: 'medium' },
  { pattern: /\b(dangerous)\b/gi, replacement: 'risky', strength: 'medium' },
  { pattern: /^(WARNING:)\s*/gi, replacement: 'Note:', strength: 'medium' },
  { pattern: /\bWARNING:\s*/gi, replacement: 'Note: ', strength: 'medium' },
  { pattern: /\b(ALARMING)\b/g, replacement: 'Notable', strength: 'medium' },
  { pattern: /\b(alarming)\b/gi, replacement: 'notable', strength: 'medium' },
  { pattern: /\b(NIGHTMARE)\b/g, replacement: 'difficult situation', strength: 'medium' },
  { pattern: /\b(nightmare)\b/gi, replacement: 'difficult situation', strength: 'medium' },
  { pattern: /\b(TERROR)\b/g, replacement: 'concern', strength: 'medium' },
  { pattern: /\b(terror)\b/gi, replacement: 'concern', strength: 'medium' },
  { pattern: /\b(WORST)\b/g, replacement: 'challenging', strength: 'medium' },
  { pattern: /\b(worst)\b/gi, replacement: 'challenging', strength: 'medium' },
  { pattern: /\b(KAREN)\b/gi, replacement: 'person', strength: 'medium' },
  { pattern: /\b(ENTITLED)\b/g, replacement: 'assertive', strength: 'medium' },
  { pattern: /\b(entitled)\b/gi, replacement: 'assertive', strength: 'medium' },
  { pattern: /\b(ENTITLEMENT)\b/g, replacement: 'behavior', strength: 'medium' },
  { pattern: /\b(entitlement)\b/gi, replacement: 'behavior', strength: 'medium' },
  { pattern: /\b(THIS IS THE END)\b/gi, replacement: 'This represents a change', strength: 'medium' },
  { pattern: /\b(THIS IS)\s+(THE|ABSOLUTE|MOST)\b/gi, replacement: 'This is', strength: 'medium' },
  { pattern: /\b(THEY (HATE|DON'T WANT))\b/gi, replacement: 'They may not prefer', strength: 'light' },
  { pattern: /\b(HATE)\b/g, replacement: 'dislike', strength: 'medium' },
  { pattern: /\b(hate)\b/gi, replacement: 'dislike', strength: 'medium' },
  { pattern: /\b(HATERS)\b/g, replacement: 'critics', strength: 'medium' },
  { pattern: /\b(TRUTH (THEY|THEY'RE|THAT))\b/gi, replacement: 'information that', strength: 'medium' },
  { pattern: /\b(THE TRUTH)\b/g, replacement: 'The information', strength: 'medium' },
  { pattern: /\b(WHAT'S REALLY)\b/gi, replacement: 'what', strength: 'light' },
  { pattern: /\b(REALLY HAPPENING)\b/gi, replacement: 'occurring', strength: 'light' },
  { pattern: /\b(CHANGES EVERYTHING)\b/gi, replacement: 'is significant', strength: 'light' },
  { pattern: /\b(GUARANTEED)\b/g, replacement: 'possibly', strength: 'light' },
  { pattern: /\b(guaranteed)\b/gi, replacement: 'possibly', strength: 'light' },
  { pattern: /\b(YOU'LL (BE|WANT TO|HATE|LOVE))\b/gi, replacement: 'You may', strength: 'light' },
  { pattern: /\b(YOU WILL)\b/gi, replacement: 'You may', strength: 'light' },
  { pattern: /\b(WILL MAKE YOU)\b/gi, replacement: 'may', strength: 'light' },
  { pattern: /\b(DON'T MISS)\b/gi, replacement: 'Consider', strength: 'light' },
  { pattern: /\b(HAVE TO SEE)\b/gi, replacement: 'may want to see', strength: 'light' },
  { pattern: /\b(HAS TO)\b/gi, replacement: 'should', strength: 'light' },
  { pattern: /\b(YOU NEED)\b/gi, replacement: 'You may want', strength: 'light' },
  { pattern: /\b(MUST SEE)\b/gi, replacement: 'worth seeing', strength: 'light' },
  { pattern: /\b(SECRET AGENDA)\b/gi, replacement: 'private plans', strength: 'medium' },
  { pattern: /\b(AGENDA)\b/g, replacement: 'plans', strength: 'light' },
  { pattern: /\b(EXPOSE)\b/g, replacement: 'reveal', strength: 'light' },
  { pattern: /\b(expose)\b/gi, replacement: 'reveal', strength: 'light' },
  { pattern: /\b(LIAR)\b/g, replacement: 'incorrect', strength: 'medium' },
  { pattern: /\b(liar)\b/gi, replacement: 'incorrect', strength: 'medium' },
  { pattern: /\b(LYING)\b/g, replacement: 'incorrect', strength: 'medium' },
  { pattern: /\b(lying)\b/gi, replacement: 'incorrect', strength: 'medium' },
  { pattern: /\b(LIES)\b/g, replacement: 'inaccuracies', strength: 'medium' },
  { pattern: /\b(lies)\b/gi, replacement: 'inaccuracies', strength: 'medium' },
  { pattern: /\b(FRAUD)\b/g, replacement: 'irregularity', strength: 'medium' },
  { pattern: /\b(fraud)\b/gi, replacement: 'irregularity', strength: 'medium' },
  { pattern: /\b(SCAM)\b/g, replacement: 'questionable practice', strength: 'medium' },
  { pattern: /\b(scam)\b/gi, replacement: 'questionable practice', strength: 'medium' },
  { pattern: /\b(RIGGED)\b/g, replacement: 'biased', strength: 'medium' },
  { pattern: /\b(rigged)\b/gi, replacement: 'biased', strength: 'medium' },
  { pattern: /\b(FAKE)\b/g, replacement: 'questionable', strength: 'medium' },
  { pattern: /\b(fake)\b/gi, replacement: 'questionable', strength: 'medium' },
  { pattern: /\b(HOAX)\b/g, replacement: 'disputed claim', strength: 'medium' },
  { pattern: /\b(hoax)\b/gi, replacement: 'disputed claim', strength: 'medium' },
  { pattern: /\b(SHILL)\b/g, replacement: 'supporter', strength: 'medium' },
  { pattern: /\b(shill)\b/gi, replacement: 'supporter', strength: 'medium' },
  { pattern: /\b(PROPAGANDA)\b/g, replacement: 'content', strength: 'medium' },
  { pattern: /\b(propaganda)\b/gi, replacement: 'content', strength: 'medium' },
  { pattern: /\b(BRAINWASH(ING|ED)?)\b/gi, replacement: 'influencing', strength: 'medium' },
  { pattern: /\b(MANIPULAT(ING|ED|ION)?)\b/gi, replacement: 'influencing', strength: 'medium' },
  { pattern: /\b(GASLIGHT(ING)?)\b/gi, replacement: 'confusing', strength: 'medium' },
  { pattern: /\b(WOKE)\b/g, replacement: 'progressive', strength: 'strict' },
  { pattern: /\b(ANTI[- ]?WAKE)\b/gi, replacement: 'traditional', strength: 'strict' },
  { pattern: /\b(SJW)\b/g, replacement: 'activist', strength: 'strict' },
  { pattern: /\b(SNOWFLAKE)\b/g, replacement: 'person', strength: 'medium' },
  { pattern: /\b(BOOMER)\b/g, replacement: 'older person', strength: 'medium' },
  { pattern: /\b(ZOOMER)\b/g, replacement: 'younger person', strength: 'medium' },
  { pattern: /\b(OK BOOMER)\b/gi, replacement: 'I disagree', strength: 'medium' },
  { pattern: /\b(TRIGGERED)\b/g, replacement: 'upset', strength: 'medium' },
  { pattern: /\b(triggered)\b/gi, replacement: 'upset', strength: 'medium' },
  { pattern: /\b(CUCK)\b/gi, replacement: 'person', strength: 'medium' },
  { pattern: /\b(SIMP)\b/gi, replacement: 'supporter', strength: 'medium' },
  { pattern: /\b(INCEL)\b/gi, replacement: 'person', strength: 'medium' },
  { pattern: /\b(NORMIE)\b/gi, replacement: 'average person', strength: 'medium' },
  { pattern: /\b(NPC)\b/g, replacement: 'person', strength: 'medium' },
  { pattern: /\b(CHAD)\b/g, replacement: 'confident person', strength: 'medium' },
  { pattern: /\b(BASED)\b/g, replacement: 'principled', strength: 'medium' },
  { pattern: /\b(CRINGE)\b/g, replacement: 'awkward', strength: 'medium' },
  { pattern: /\b(cringe)\b/gi, replacement: 'awkward', strength: 'medium' },
  { pattern: /\b(CRINGEY)\b/g, replacement: 'awkward', strength: 'medium' },
  { pattern: /\b(CRINGY)\b/g, replacement: 'awkward', strength: 'medium' },
  { pattern: /\b(YIKES)\b/g, replacement: 'notable', strength: 'light' },
  { pattern: /\b(OOF)\b/g, replacement: 'unfortunate', strength: 'light' },
  { pattern: /\b(YEET)\b/g, replacement: 'discard', strength: 'light' },
  { pattern: /\b(NO CAP)\b/gi, replacement: 'honestly', strength: 'light' },
  { pattern: /\b(CAP)\b/g, replacement: 'exaggeration', strength: 'light' },
  { pattern: /\b(BET)\b/g, replacement: 'agreed', strength: 'light' },
  { pattern: /\b(SLAY)\b/g, replacement: 'succeed', strength: 'light' },
  { pattern: /\b(ICONIC)\b/g, replacement: 'memorable', strength: 'light' },
  { pattern: /\b(LEGENDARY)\b/g, replacement: 'notable', strength: 'light' },
  { pattern: /\b(GOAT)\b/g, replacement: 'greatest', strength: 'light' },
  { pattern: /\b(FIRE)\b/g, replacement: 'good', strength: 'light' },
  { pattern: /\b(LIT)\b/g, replacement: 'exciting', strength: 'light' },
  { pattern: /\b(DOPE)\b/g, replacement: 'good', strength: 'light' },
  { pattern: /\b(SICK!)\b/g, replacement: 'impressive', strength: 'light' },
  { pattern: /\b(WILD)\b/g, replacement: 'unusual', strength: 'light' },
  { pattern: /\b(THROW YOUR PHONE)\b/gi, replacement: 'be frustrated', strength: 'medium' },
  { pattern: /\b(THROW (MY|YOUR|HIS|HER) PHONE)\b/gi, replacement: 'be frustrated', strength: 'medium' },
  { pattern: /\b(WANT TO THROW)\b/gi, replacement: 'be frustrated by', strength: 'medium' },
  { pattern: /\b(PUNCH (MY|THE|A) SCREEN)\b/gi, replacement: 'be frustrated', strength: 'medium' },
  { pattern: /\b(SCREAM(ING)? AT (MY|THE) SCREEN)\b/gi, replacement: 'frustrated', strength: 'medium' },
  { pattern: /\b(RAGE QUIT)\b/gi, replacement: 'stop', strength: 'medium' },
  { pattern: /\b(UNSUBSCRIBE)\b/g, replacement: 'disagree', strength: 'light' },
  { pattern: /\b(DISLIKE)\b/g, replacement: 'disagree', strength: 'light' },
  { pattern: /\b(RATIO)\b/g, replacement: 'response', strength: 'light' },
  { pattern: /\b(L)\b/g, replacement: 'loss', strength: 'light' },
  { pattern: /\b(W)\b/g, replacement: 'success', strength: 'light' },
  { pattern: /\b(F IN CHAT)\b/gi, replacement: 'acknowledgment', strength: 'light' },
  { pattern: /\b(RIP)\b/g, replacement: 'unfortunate', strength: 'light' },
  { pattern: /\b(DEAD)\b/g, replacement: 'amused', strength: 'light' },
  { pattern: /\b(I'M DEAD)\b/gi, replacement: 'amused', strength: 'light' },
  { pattern: /\b(DYING)\b/g, replacement: 'very amused', strength: 'light' },
  { pattern: /\b(I CAN'T)\b/g, replacement: 'notable', strength: 'light' },
  { pattern: /\b(I CAN'T EVEN)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(SAME)\b/g, replacement: 'I agree', strength: 'light' },
  { pattern: /\b(MOOD)\b/g, replacement: 'feeling', strength: 'light' },
  { pattern: /\b(BIG MOOD)\b/gi, replacement: 'strong feeling', strength: 'light' },
  { pattern: /\b(REAL)\b/g, replacement: 'accurate', strength: 'light' },
  { pattern: /\b(FR)\b/g, replacement: 'honestly', strength: 'light' },
  { pattern: /\b(LOWKEY)\b/g, replacement: 'somewhat', strength: 'light' },
  { pattern: /\b(HIGHKEY)\b/g, replacement: 'definitely', strength: 'light' },
  { pattern: /\b(LOW KEY)\b/gi, replacement: 'somewhat', strength: 'light' },
  { pattern: /\b(HIGH KEY)\b/gi, replacement: 'definitely', strength: 'light' },
  { pattern: /\b(LEGIT)\b/g, replacement: 'genuinely', strength: 'light' },
  { pattern: /\b(LEGITIMATELY)\b/g, replacement: 'genuinely', strength: 'light' },
  { pattern: /\b(FOR REAL)\b/gi, replacement: 'genuinely', strength: 'light' },
  { pattern: /\b(NO LIE)\b/gi, replacement: 'honestly', strength: 'light' },
  { pattern: /\b(FR FR)\b/gi, replacement: 'honestly', strength: 'light' },
  { pattern: /\b(PERIODT?)\b/gi, replacement: 'definitively', strength: 'light' },
  { pattern: /\b(PERIODT)\b/gi, replacement: 'definitively', strength: 'light' },
  { pattern: /\b(AND I MEAN IT)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(SAY IT LOUDER)\b/gi, replacement: 'I agree', strength: 'light' },
  { pattern: /\b(SAY IT WITH ME)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(CAN WE TALK ABOUT)\b/gi, replacement: 'Consider', strength: 'light' },
  { pattern: /\b(LET'S TALK ABOUT)\b/gi, replacement: 'Consider', strength: 'light' },
  { pattern: /\b(WE NEED TO TALK ABOUT)\b/gi, replacement: 'Consider', strength: 'light' },
  { pattern: /\b(I HAVE THOUGHTS)\b/gi, replacement: 'I have opinions', strength: 'light' },
  { pattern: /\b(THOUGHTS\?)\b/g, replacement: 'Opinions?', strength: 'light' },
  { pattern: /\b(HOT TAKE)\b/gi, replacement: 'opinion', strength: 'light' },
  { pattern: /\b(UNPOPULAR OPINION)\b/gi, replacement: 'opinion', strength: 'light' },
  { pattern: /\b(POPULAR OPINION)\b/gi, replacement: 'common view', strength: 'light' },
  { pattern: /\b(SPOILER ALERT)\b/gi, replacement: 'note', strength: 'light' },
  { pattern: /\b(MAJOR SPOILER)\b/gi, replacement: 'note', strength: 'light' },
  { pattern: /\b(SPOILER)\b/g, replacement: 'detail', strength: 'light' },
  { pattern: /\b(PLOT TWIST)\b/gi, replacement: 'development', strength: 'light' },
  { pattern: /\b(REVEAL)\b/g, replacement: 'detail', strength: 'light' },
  { pattern: /\b(CLIFFHANGER)\b/g, replacement: 'suspenseful ending', strength: 'light' },
  { pattern: /\b(TWIST ENDING)\b/gi, replacement: 'unexpected ending', strength: 'light' },
  { pattern: /\b(TWIST)\b/g, replacement: 'development', strength: 'light' },
  { pattern: /\b(JAW[- ]?DROP(PING)?)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(GENIUS(ES)?)\b/gi, replacement: 'smart person', strength: 'light' },
  { pattern: /\b(BRIDEZILLA)\b/gi, replacement: 'stressed bride', strength: 'medium' },
  { pattern: /\b(PRICELESS)\b/g, replacement: 'Notable', strength: 'light' },
  { pattern: /\b(priceless)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(IN TEARS)\b/gi, replacement: 'emotional', strength: 'light' },
  { pattern: /\b(DELUSIONAL)\b/g, replacement: 'mistaken', strength: 'medium' },
  { pattern: /\b(delusional)\b/gi, replacement: 'mistaken', strength: 'medium' },
  { pattern: /\b(PATHETIC)\b/g, replacement: 'Unfortunate', strength: 'medium' },
  { pattern: /\b(pathetic)\b/gi, replacement: 'unfortunate', strength: 'medium' },
  { pattern: /\b(CONTEMPT)\b/g, replacement: 'disagreement', strength: 'medium' },
  { pattern: /\b(contempt)\b/gi, replacement: 'disagreement', strength: 'medium' },
  { pattern: /\b(CRIMINAL)\b/g, replacement: 'Questionable', strength: 'medium' },
  { pattern: /\b(criminal)\b/gi, replacement: 'questionable', strength: 'medium' },
  { pattern: /\b(LOCKED UP)\b/gi, replacement: 'held accountable', strength: 'medium' },
  { pattern: /\b(WASTES? OF OXYGEN)\b/gi, replacement: 'people', strength: 'medium' },
  { pattern: /\b(WASTE OF SPACE)\b/gi, replacement: 'person', strength: 'medium' },
  { pattern: /\b(WORST PERSON)\b/gi, replacement: 'challenging person', strength: 'medium' },
  { pattern: /\b(THE WORST)\b/g, replacement: 'challenging', strength: 'medium' },
  { pattern: /\b(TERRIBLY)\b/g, replacement: 'Poorly', strength: 'light' },
  { pattern: /\b(terribly)\b/gi, replacement: 'poorly', strength: 'light' },
  { pattern: /\b(LITERALLY DYING)\b/gi, replacement: 'very amused', strength: 'light' },
  { pattern: /\b(LITERALLY)\b/g, replacement: 'Seriously', strength: 'light' },
  { pattern: /\b(CAN'T EVEN)\b/gi, replacement: 'am affected', strength: 'light' },
  { pattern: /\b(I CAN'T)\b/g, replacement: 'Notable', strength: 'light' },
  { pattern: /\b(IMMEDIATELY)\b/g, replacement: 'Soon', strength: 'light' },
  { pattern: /\b(immediately)\b/gi, replacement: 'soon', strength: 'light' },
  { pattern: /\b(RIGHT NOW)\b/g, replacement: 'now', strength: 'light' },
  { pattern: /\b(right now)\b/gi, replacement: 'now', strength: 'light' },
  { pattern: /\b(THIS VERY MOMENT)\b/gi, replacement: 'now', strength: 'light' },
  { pattern: /\b(BEFORE IT'S TOO LATE)\b/gi, replacement: 'soon', strength: 'medium' },
  { pattern: /\b(TOO LATE)\b/g, replacement: 'delayed', strength: 'medium' },
  { pattern: /\b(INSANE)\b/g, replacement: 'Unusual', strength: 'medium' },
  { pattern: /\b(ABSOLUTELY)\b/g, replacement: 'Very', strength: 'light' },
  { pattern: /\b(absolutely)\b/gi, replacement: 'very', strength: 'light' },
  { pattern: /\b(COMPLETELY)\b/g, replacement: 'Very', strength: 'light' },
  { pattern: /\b(completely)\b/gi, replacement: 'very', strength: 'light' },
  { pattern: /\b(TOTALLY)\b/g, replacement: 'Very', strength: 'light' },
  { pattern: /\b(totally)\b/gi, replacement: 'very', strength: 'light' },
  { pattern: /\b(UTTERLY)\b/g, replacement: 'Very', strength: 'light' },
  { pattern: /\b(utterly)\b/gi, replacement: 'very', strength: 'light' },
  { pattern: /\b(DEVESTATED)\b/gi, replacement: 'affected', strength: 'medium' },
  { pattern: /\b(DEVASTATING)\b/g, replacement: 'Significant', strength: 'medium' },
  { pattern: /\b(devastating)\b/gi, replacement: 'significant', strength: 'medium' },
  { pattern: /\b(HEARTBROKEN)\b/gi, replacement: 'disappointed', strength: 'medium' },
  { pattern: /\b(HEARTBREAKING)\b/gi, replacement: 'sad', strength: 'medium' },
  { pattern: /\b(EMBARRASSING)\b/g, replacement: 'Unusual', strength: 'medium' },
  { pattern: /\b(embarrassing)\b/gi, replacement: 'unusual', strength: 'medium' },
  { pattern: /\b(EMBARRASSED)\b/gi, replacement: 'uncomfortable', strength: 'medium' },
  { pattern: /\b(HUMILIATED)\b/gi, replacement: 'uncomfortable', strength: 'medium' },
  { pattern: /\b(HUMILIATES?)\b/gi, replacement: 'affects', strength: 'medium' },
  { pattern: /\b(HUMILIATING)\b/gi, replacement: 'unusual', strength: 'medium' },
  { pattern: /\b(DISGRACE(FUL)?)\b/gi, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(SHAME(FUL)?)\b/gi, replacement: 'unfortunate', strength: 'medium' },
  { pattern: /\b(SHAME ON)\b/gi, replacement: 'consider', strength: 'medium' },
  { pattern: /\b(UNTHINKABLE)\b/g, replacement: 'Unusual', strength: 'medium' },
  { pattern: /\b(unthinkable)\b/gi, replacement: 'unusual', strength: 'medium' },
  { pattern: /\b(INDESCRIBABLE)\b/g, replacement: 'Notable', strength: 'light' },
  { pattern: /\b(indescribable)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(BEYOND WORDS)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(NO WORDS)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(FORGET)\b/g, replacement: 'Note', strength: 'light' },
  { pattern: /\b(FORGET TO)\b/gi, replacement: 'remember to', strength: 'light' },
  { pattern: /\b(WON'T FORGET)\b/gi, replacement: 'will remember', strength: 'light' },
  { pattern: /\b(NEVER FORGET)\b/gi, replacement: 'remember', strength: 'light' },
  { pattern: /\b(WILL BE REMEMBERED)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(FOREVER)\b/g, replacement: 'For a long time', strength: 'light' },
  { pattern: /\b(forever)\b/gi, replacement: 'for a long time', strength: 'light' },
  { pattern: /\b(ETERNITY)\b/gi, replacement: 'a long time', strength: 'light' },
  { pattern: /\b(CHANGE YOUR LIFE)\b/gi, replacement: 'affect you', strength: 'light' },
  { pattern: /\b(CHANGED MY LIFE)\b/gi, replacement: 'affected me', strength: 'light' },
  { pattern: /\b(LIFE-CHANGING)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(LIFE ALTERING)\b/gi, replacement: 'significant', strength: 'light' },
  { pattern: /\b(PROVE THEM WRONG)\b/gi, replacement: 'demonstrate', strength: 'medium' },
  { pattern: /\b(PROVED THEM WRONG)\b/gi, replacement: 'demonstrated', strength: 'medium' },
  { pattern: /\b(PROVE EVERYONE WRONG)\b/gi, replacement: 'demonstrate', strength: 'medium' },
  { pattern: /\b(EXPOSED)\b/g, replacement: 'Revealed', strength: 'light' },
  { pattern: /\b(EXPOSES?)\b/gi, replacement: 'reveals', strength: 'light' },
  { pattern: /\b(GETS EXPOSED)\b/gi, replacement: 'is revealed', strength: 'light' },
  { pattern: /\b(BANNED)\b/g, replacement: 'Restricted', strength: 'light' },
  { pattern: /\b(banned)\b/gi, replacement: 'restricted', strength: 'light' },
  { pattern: /\b(CENSORED)\b/gi, replacement: 'filtered', strength: 'medium' },
  { pattern: /\b(CENSORSHIP)\b/gi, replacement: 'filtering', strength: 'medium' },
  { pattern: /\b(WENT VIRAL)\b/gi, replacement: 'became popular', strength: 'light' },
  { pattern: /\b(VIRAL)\b/g, replacement: 'Popular', strength: 'light' },
  { pattern: /\b(viral)\b/gi, replacement: 'popular', strength: 'light' },
  { pattern: /\b(BREAK THE INTERNET)\b/gi, replacement: 'become popular', strength: 'light' },
  { pattern: /\b(TRENDING)\b/g, replacement: 'Popular', strength: 'light' },
  { pattern: /\b(trending)\b/gi, replacement: 'popular', strength: 'light' },
  { pattern: /\b(MELTDOWN)\b/g, replacement: 'Reaction', strength: 'medium' },
  { pattern: /\b(meltdown)\b/gi, replacement: 'reaction', strength: 'medium' },
  { pattern: /\b(IN FREEFALL)\b/gi, replacement: 'declining', strength: 'medium' },
  { pattern: /\b(PLUMMET(ING)?)\b/gi, replacement: 'declining', strength: 'medium' },
  { pattern: /\b(THROUGH THE ROOF)\b/gi, replacement: 'increasing', strength: 'light' },
  { pattern: /\b(OFF THE CHARTS)\b/gi, replacement: 'high', strength: 'light' },
  { pattern: /\b(OFF THE RAILS)\b/gi, replacement: 'chaotic', strength: 'medium' },
  { pattern: /\b(OUT OF CONTROL)\b/gi, replacement: 'unmanaged', strength: 'medium' },
  { pattern: /\b(RUNNING SCARED)\b/gi, replacement: 'concerned', strength: 'medium' },
  { pattern: /\b(RUNNING FOR COVER)\b/gi, replacement: 'responding', strength: 'medium' },
  { pattern: /\b(SCRAMBLING)\b/gi, replacement: 'working', strength: 'medium' },
  { pattern: /\b(PANICKING)\b/gi, replacement: 'concerned', strength: 'medium' },
  { pattern: /\b(PANIC)\b/g, replacement: 'Concern', strength: 'medium' },
  { pattern: /\b(panic)\b/gi, replacement: 'concern', strength: 'medium' },
  { pattern: /\b(HYSTERIA)\b/gi, replacement: 'reaction', strength: 'medium' },
  { pattern: /\b(HYSTERICAL)\b/gi, replacement: 'emotional', strength: 'medium' },
  { pattern: /\b(FREAK(ING|S|ED)? OUT)\b/gi, replacement: 'reacting', strength: 'medium' },
  { pattern: /\b(FREAK)\b/g, replacement: 'Person', strength: 'medium' },
  { pattern: /\b(RANT)\b/g, replacement: 'Commentary', strength: 'medium' },
  { pattern: /\b(rant)\b/gi, replacement: 'commentary', strength: 'medium' },
  { pattern: /\b(RAGING)\b/g, replacement: 'Concerned', strength: 'medium' },
  { pattern: /\b(FUMING)\b/g, replacement: 'Frustrated', strength: 'medium' },
  { pattern: /\b(fuming)\b/gi, replacement: 'frustrated', strength: 'medium' },
  { pattern: /\b(STEAM(ING)?)\b/gi, replacement: 'frustrated', strength: 'medium' },
  { pattern: /\b(BLOW(ING)? UP)\b/gi, replacement: 'expanding', strength: 'medium' },
  { pattern: /\b(BLEW UP)\b/gi, replacement: 'expanded', strength: 'medium' },
  { pattern: /\b(ERUPT(ED|ING|S)?)\b/gi, replacement: 'developed', strength: 'medium' },
  { pattern: /\b(EXPLODE(S|D|ING)?)\b/gi, replacement: 'expand', strength: 'medium' },
  { pattern: /\b(IMPLODE(S|D|ING)?)\b/gi, replacement: 'collapse', strength: 'medium' },
  { pattern: /\b(COLLAPSE(S|D|ING)?)\b/gi, replacement: 'fail', strength: 'medium' },
  { pattern: /\b(CRUMBLE(S|D|ING)?)\b/gi, replacement: 'fail', strength: 'medium' },
  { pattern: /\b(CRASH(ING|ES|ED)?)\b/gi, replacement: 'fail', strength: 'medium' },
  { pattern: /\b(PLUNGE(S|D)?)\b/gi, replacement: 'drop', strength: 'medium' },
  { pattern: /\b(SOAR(ING|S|ED)?)\b/gi, replacement: 'rise', strength: 'medium' },
  { pattern: /\b(SURGE(S|D)?)\b/gi, replacement: 'increase', strength: 'medium' },
  { pattern: /\b(SKYROCKET(ING|S|ED)?)\b/gi, replacement: 'increase', strength: 'medium' },
  { pattern: /\b(SPIKE(S|D)?)\b/gi, replacement: 'increase', strength: 'medium' },
  { pattern: /\b(WENT TOO FAR)\b/gi, replacement: 'was excessive', strength: 'medium' },
  { pattern: /\b(CROSSED THE LINE)\b/gi, replacement: 'was excessive', strength: 'medium' },
  { pattern: /\b(OVER THE TOP)\b/gi, replacement: 'excessive', strength: 'medium' },
  { pattern: /\b(TOO FAR)\b/g, replacement: 'Excessive', strength: 'medium' },
  { pattern: /\b(ATROCITY)\b/gi, replacement: 'problematic event', strength: 'medium' },
  { pattern: /\b(ATROCIOUS)\b/g, replacement: 'Problematic', strength: 'medium' },
  { pattern: /\b(DEPRAVITY)\b/gi, replacement: 'problematic behavior', strength: 'medium' },
  { pattern: /\b(DEPRAVED)\b/gi, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(NAUSEATING)\b/gi, replacement: 'unpleasant', strength: 'medium' },
  { pattern: /\b(REPULSIVE)\b/gi, replacement: 'unpleasant', strength: 'medium' },
  { pattern: /\b(REVOLTING)\b/gi, replacement: 'unpleasant', strength: 'medium' },
  { pattern: /\b(VILE)\b/g, replacement: 'Problematic', strength: 'medium' },
  { pattern: /\b(vile)\b/gi, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(FILTH)\b/gi, replacement: 'problematic content', strength: 'medium' },
  { pattern: /\b(FILTHY)\b/gi, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(SCUM)\b/gi, replacement: 'people', strength: 'medium' },
  { pattern: /\b(VERMIN)\b/gi, replacement: 'people', strength: 'medium' },
  { pattern: /\b(DEGENERATE)\b/gi, replacement: 'person', strength: 'medium' },
  { pattern: /\b(LOWLIFE)\b/gi, replacement: 'person', strength: 'medium' },
  { pattern: /\b(PIECE OF WORK)\b/gi, replacement: 'person', strength: 'medium' },
  { pattern: /\b(WASTE OF TIME)\b/gi, replacement: 'not useful', strength: 'light' },
  { pattern: /\b(WASTE OF MONEY)\b/gi, replacement: 'not valuable', strength: 'light' },
  { pattern: /\b(TOTAL WASTE)\b/gi, replacement: 'not useful', strength: 'light' },
  { pattern: /\b(RIP-OFF)\b/gi, replacement: 'overpriced', strength: 'medium' },
  { pattern: /\b(SCAMMED)\b/gi, replacement: 'deceived', strength: 'medium' },
  { pattern: /\b(RIPPED OFF)\b/gi, replacement: 'deceived', strength: 'medium' },
  { pattern: /\b(PLAYED)\b/g, replacement: 'Deceived', strength: 'medium' },
  { pattern: /\b(GOT PLAYED)\b/gi, replacement: 'was deceived', strength: 'medium' },
  { pattern: /\b(TAKEN FOR A RIDE)\b/gi, replacement: 'deceived', strength: 'medium' },
  { pattern: /\b(TOOK ADVANTAGE)\b/gi, replacement: 'used', strength: 'medium' },
  { pattern: /\b(EXPLOITED)\b/gi, replacement: 'used', strength: 'medium' },
  { pattern: /\b(VICTIM)\b/g, replacement: 'Person', strength: 'medium' },
  { pattern: /\b(VICTIMIZED)\b/gi, replacement: 'affected', strength: 'medium' },
  { pattern: /\b(PREY(ED|ING)? ON)\b/gi, replacement: 'target', strength: 'medium' },
  { pattern: /\b(TARGET(ED|ING|S)?)\b/g, replacement: 'Targeted', strength: 'medium' },
  { pattern: /\b(TARGETED)\b/gi, replacement: 'targeted', strength: 'medium' },
  { pattern: /\b(SINGLED OUT)\b/gi, replacement: 'selected', strength: 'medium' },
  { pattern: /\b(PICKED ON)\b/gi, replacement: 'criticized', strength: 'medium' },
  { pattern: /\b(BULLIED)\b/gi, replacement: 'harassed', strength: 'medium' },
  { pattern: /\b(HARASS(ED|ING|MENT)?)\b/gi, replacement: 'bother', strength: 'medium' },
  { pattern: /\b(TORMENT(ED|ING)?)\b/gi, replacement: 'bother', strength: 'medium' },
  { pattern: /\b(TORTURE(D|D)?)\b/gi, replacement: 'troubled', strength: 'medium' },
  { pattern: /\b(TORMENT)\b/g, replacement: 'Distress', strength: 'medium' },
  { pattern: /\b(HELL)\b/g, replacement: 'difficulty', strength: 'medium' },
  { pattern: /\b(HELLISH)\b/gi, replacement: 'difficult', strength: 'medium' },
  { pattern: /\b(LIVING HELL)\b/gi, replacement: 'very difficult', strength: 'medium' },
  { pattern: /\b(NIGHTMARE)\b/g, replacement: 'Difficult situation', strength: 'medium' },
  { pattern: /\b(ABSOLUTE HELL)\b/gi, replacement: 'very difficult', strength: 'medium' },
  { pattern: /\b(PURE HELL)\b/gi, replacement: 'very difficult', strength: 'medium' },
  { pattern: /\b(WAR ZONE)\b/gi, replacement: 'conflict area', strength: 'medium' },
  { pattern: /\b(BATTLEFIELD)\b/gi, replacement: 'conflict', strength: 'medium' },
  { pattern: /\b(BLOODSHED)\b/gi, replacement: 'violence', strength: 'medium' },
  { pattern: /\b(CARNAGE)\b/gi, replacement: 'destruction', strength: 'medium' },
  { pattern: /\b(SLAUGHTER)\b/gi, replacement: 'defeat', strength: 'medium' },
  { pattern: /\b(MASSACRE)\b/gi, replacement: 'defeat', strength: 'medium' },
  { pattern: /\b(ANNIHILATE(D|D)?)\b/gi, replacement: 'defeat', strength: 'medium' },
  { pattern: /\b(DECIMATE(D|D)?)\b/gi, replacement: 'reduce', strength: 'medium' },
  { pattern: /\b(OBLITERATE(D|D)?)\b/gi, replacement: 'remove', strength: 'medium' },
  { pattern: /\b(ERASED)\b/gi, replacement: 'removed', strength: 'medium' },
  { pattern: /\b(WIPED OUT)\b/gi, replacement: 'removed', strength: 'medium' },
  { pattern: /\b(WIPED FROM)\b/gi, replacement: 'removed from', strength: 'medium' },
  { pattern: /\b(WIPED OFF)\b/gi, replacement: 'removed from', strength: 'medium' },
  { pattern: /\b(VANISHED)\b/gi, replacement: 'disappeared', strength: 'light' },
  { pattern: /\b(DISAPPEARED)\b/gi, replacement: 'gone', strength: 'light' },
  { pattern: /\b(GONE MISSING)\b/gi, replacement: 'absent', strength: 'light' },
  { pattern: /\b(NO TRACE)\b/gi, replacement: 'not found', strength: 'light' },
  { pattern: /\b(WHEREABOUTS UNKNOWN)\b/gi, replacement: 'location unknown', strength: 'light' },
  { pattern: /\b(NEVER SEEN AGAIN)\b/gi, replacement: 'not found', strength: 'light' },
  { pattern: /\b(NEVER TO BE SEEN)\b/gi, replacement: 'absent', strength: 'light' },
  { pattern: /\b(FATE UNKNOWN)\b/gi, replacement: 'status unknown', strength: 'light' },
  { pattern: /\b(UNACCOUNTED FOR)\b/gi, replacement: 'not found', strength: 'light' },
  { pattern: /\b(DATA BREACH)\b/gi, replacement: 'security incident', strength: 'medium' },
  { pattern: /\b(HACKED)\b/gi, replacement: 'accessed', strength: 'medium' },
  { pattern: /\b(HACKER)\b/gi, replacement: 'attacker', strength: 'medium' },
  { pattern: /\b(CYBERATTACK)\b/gi, replacement: 'online incident', strength: 'medium' },
  { pattern: /\b(RANSOMWARE)\b/gi, replacement: 'malicious software', strength: 'medium' },
  { pattern: /\b(MALWARE)\b/gi, replacement: 'unwanted software', strength: 'medium' },
  { pattern: /\b(VIRUS)\b/g, replacement: 'Program', strength: 'medium' },
  { pattern: /\b(SPYING)\b/gi, replacement: 'monitoring', strength: 'medium' },
  { pattern: /\b(SPY)\b/g, replacement: 'Monitor', strength: 'medium' },
  { pattern: /\b(SPIED)\b/gi, replacement: 'monitored', strength: 'medium' },
  { pattern: /\b(STOLE)\b/gi, replacement: 'took', strength: 'medium' },
  { pattern: /\b(STOLEN)\b/gi, replacement: 'taken', strength: 'medium' },
  { pattern: /\b(STEAL)\b/g, replacement: 'Take', strength: 'medium' },
  { pattern: /\b(STEALING)\b/gi, replacement: 'taking', strength: 'medium' },
  { pattern: /\b(THIEF)\b/gi, replacement: 'person', strength: 'medium' },
  { pattern: /\b(THEFT)\b/g, replacement: 'Taking', strength: 'medium' },
  { pattern: /\b(ROBBERY)\b/gi, replacement: 'theft', strength: 'medium' },
  { pattern: /\b(ROBBED)\b/gi, replacement: 'taken from', strength: 'medium' },
  { pattern: /\b(BREACH)\b/g, replacement: 'Incident', strength: 'medium' },
  { pattern: /\b(LEAK)\b/g, replacement: 'Release', strength: 'medium' },
  { pattern: /\b(LEAKED)\b/gi, replacement: 'released', strength: 'medium' },
  { pattern: /\b(LEAKING)\b/gi, replacement: 'releasing', strength: 'medium' },
  { pattern: /\b(EXPOSE)\b/g, replacement: 'Reveal', strength: 'medium' },
  { pattern: /\b(VULNERABILITY)\b/gi, replacement: 'issue', strength: 'medium' },
  { pattern: /\b(VULNERABLE)\b/gi, replacement: 'at risk', strength: 'medium' },
  { pattern: /\b(EXPLOIT)\b/g, replacement: 'Use', strength: 'medium' },
  { pattern: /\b(EXPLOITED)\b/gi, replacement: 'used', strength: 'medium' },
  { pattern: /\b(FLAW)\b/g, replacement: 'Issue', strength: 'medium' },
  { pattern: /\b(BUG)\b/g, replacement: 'Issue', strength: 'light' },
  { pattern: /\b(GLITCH)\b/gi, replacement: 'error', strength: 'light' },
  { pattern: /\b(CRASH)\b/g, replacement: 'Fail', strength: 'medium' },
  { pattern: /\b(CRASHED)\b/gi, replacement: 'failed', strength: 'medium' },
  { pattern: /\b(OUTAGE)\b/g, replacement: 'Interruption', strength: 'medium' },
  { pattern: /\b(DOWN)\b/g, replacement: 'Unavailable', strength: 'light' },
  { pattern: /\b(BROKE)\b/g, replacement: 'Failed', strength: 'medium' },
  { pattern: /\b(BROKEN)\b/gi, replacement: 'not working', strength: 'medium' },
  { pattern: /\b(FIX)\b/g, replacement: 'Update', strength: 'light' },
  { pattern: /\b(FIXED)\b/gi, replacement: 'updated', strength: 'light' },
  { pattern: /\b(URGENT FIX)\b/gi, replacement: 'update', strength: 'medium' },
  { pattern: /\b(CRITICAL UPDATE)\b/gi, replacement: 'update', strength: 'medium' },
  { pattern: /\b(SECURITY FLAW)\b/gi, replacement: 'security issue', strength: 'medium' },
  { pattern: /\b(CRITICAL FLAW)\b/gi, replacement: 'issue', strength: 'medium' },
  { pattern: /\b(MAJOR BUG)\b/gi, replacement: 'issue', strength: 'medium' },
  { pattern: /\b(SERIOUS ISSUE)\b/gi, replacement: 'issue', strength: 'medium' },
  { pattern: /\b(DRAINING)\b/g, replacement: 'Using', strength: 'medium' },
  { pattern: /\b(DRAINED)\b/gi, replacement: 'used', strength: 'medium' },
  { pattern: /\b(DRAIN)\b/g, replacement: 'Use', strength: 'medium' },
  { pattern: /\b(SUCKING)\b/gi, replacement: 'using', strength: 'medium' },
  { pattern: /\b(EATING UP)\b/gi, replacement: 'using', strength: 'medium' },
  { pattern: /\b(GOBBLING)\b/gi, replacement: 'using', strength: 'medium' },
  { pattern: /\b(DESTROYING YOUR)\b/gi, replacement: 'affecting your', strength: 'medium' },
  { pattern: /\b(KILLING YOUR)\b/gi, replacement: 'affecting your', strength: 'medium' },
  { pattern: /\b(RUINING)\b/gi, replacement: 'affecting', strength: 'medium' },
  { pattern: /\b(WRECKING)\b/gi, replacement: 'affecting', strength: 'medium' },
  { pattern: /\b(TRACK)\b/g, replacement: 'Monitor', strength: 'medium' },
  { pattern: /\b(TRACKING)\b/gi, replacement: 'monitoring', strength: 'medium' },
  { pattern: /\b(TRACKED)\b/gi, replacement: 'monitored', strength: 'medium' },
  { pattern: /\b(MONITOR)\b/g, replacement: 'Observe', strength: 'light' },
  { pattern: /\b(SURVEILLANCE)\b/gi, replacement: 'monitoring', strength: 'medium' },
  { pattern: /\b(WATCHING)\b/g, replacement: 'Observing', strength: 'medium' },
  { pattern: /\b(WATCHED)\b/gi, replacement: 'observed', strength: 'medium' },
  { pattern: /\b(RECORDED)\b/gi, replacement: 'saved', strength: 'medium' },
  { pattern: /\b(RECORDING)\b/g, replacement: 'Saving', strength: 'medium' },
  { pattern: /\b(COLLECTING)\b/gi, replacement: 'saving', strength: 'medium' },
  { pattern: /\b(COLLECTED)\b/gi, replacement: 'saved', strength: 'medium' },
  { pattern: /\b(GATHERING)\b/g, replacement: 'Collecting', strength: 'light' },
  { pattern: /\b(HARVESTING)\b/gi, replacement: 'collecting', strength: 'medium' },
  { pattern: /\b(SELLING YOUR)\b/gi, replacement: 'sharing your', strength: 'medium' },
  { pattern: /\b(SELLS YOUR)\b/gi, replacement: 'shares your', strength: 'medium' },
  { pattern: /\b(SOLD YOUR)\b/gi, replacement: 'shared your', strength: 'medium' },
  { pattern: /\b(COMPRIMISED)\b/gi, replacement: 'accessed', strength: 'medium' },
  { pattern: /\b(COMPRIMISE)\b/gi, replacement: 'affect', strength: 'medium' },
  { pattern: /\b(AFFECTED)\b/g, replacement: 'Impacted', strength: 'light' },
  { pattern: /\b(IMMINENT)\b/g, replacement: 'Possible', strength: 'medium' },
  { pattern: /\b(INEVITABLE)\b/gi, replacement: 'likely', strength: 'medium' },
  { pattern: /\b(UNAVOIDABLE)\b/gi, replacement: 'likely', strength: 'medium' },
  { pattern: /\b(CERTAIN)\b/g, replacement: 'Likely', strength: 'light' },
  { pattern: /\b(GUARANTEED TO)\b/gi, replacement: 'likely to', strength: 'light' },
  { pattern: /\b(WILL DEFINITELY)\b/gi, replacement: 'will likely', strength: 'light' },
  { pattern: /\b(WILL SURELY)\b/gi, replacement: 'will likely', strength: 'light' },
  { pattern: /\b(WILL WITHOUT DOUBT)\b/gi, replacement: 'will likely', strength: 'light' },
  { pattern: /\b(WITHOUT A DOUBT)\b/gi, replacement: 'likely', strength: 'light' },
  { pattern: /\b(NO DOUBT)\b/gi, replacement: 'likely', strength: 'light' },
  { pattern: /\b(ABSOLUTELY WILL)\b/gi, replacement: 'will likely', strength: 'light' },
  { pattern: /\b(COULD WIPE OUT)\b/gi, replacement: 'could affect', strength: 'medium' },
  { pattern: /\b(WIPE OUT)\b/gi, replacement: 'affect', strength: 'medium' },
  { pattern: /\b(WIPED OUT)\b/gi, replacement: 'affected', strength: 'medium' },
  { pattern: /\b(EXTINCTION)\b/gi, replacement: 'reduction', strength: 'medium' },
  { pattern: /\b(EXTINCT)\b/gi, replacement: 'gone', strength: 'medium' },
  { pattern: /\b(WIPE US OUT)\b/gi, replacement: 'affect us', strength: 'medium' },
  { pattern: /\b(END OF DAYS)\b/gi, replacement: 'significant change', strength: 'medium' },
  { pattern: /\b(END TIMES)\b/gi, replacement: 'significant change', strength: 'medium' },
  { pattern: /\b(APOCALYPSE)\b/gi, replacement: 'major change', strength: 'medium' },
  { pattern: /\b(APOCALYPTIC)\b/gi, replacement: 'significant', strength: 'medium' },
  { pattern: /\b(ARMAGEDDON)\b/gi, replacement: 'significant event', strength: 'medium' },
  { pattern: /\b(DOOMSDAY)\b/gi, replacement: 'significant day', strength: 'medium' },
  { pattern: /\b(DOOM)\b/g, replacement: 'Concern', strength: 'medium' },
  { pattern: /\b(DOOMED)\b/gi, replacement: 'in trouble', strength: 'medium' },
  { pattern: /\b(DOOMING)\b/gi, replacement: 'affecting', strength: 'medium' },
  { pattern: /\b(WORTHLESS)\b/gi, replacement: 'less valuable', strength: 'medium' },
  { pattern: /\b(USELESS)\b/gi, replacement: 'not useful', strength: 'medium' },
  { pattern: /\b(POINTLESS)\b/gi, replacement: 'not useful', strength: 'medium' },
  { pattern: /\b(FUTILE)\b/gi, replacement: 'unlikely to succeed', strength: 'medium' },
  { pattern: /\b(HOPELESS)\b/gi, replacement: 'difficult', strength: 'medium' },
  { pattern: /\b(NO HOPE)\b/gi, replacement: 'difficult', strength: 'medium' },
  { pattern: /\b(ALL HOPE LOST)\b/gi, replacement: 'challenging', strength: 'medium' },
  { pattern: /\b(LOST HOPE)\b/gi, replacement: 'concerned', strength: 'medium' },
  { pattern: /\b(GIVE UP)\b/gi, replacement: 'stop', strength: 'medium' },
  { pattern: /\b(SURRENDER)\b/gi, replacement: 'stop', strength: 'medium' },
  { pattern: /\b(NO CHANCE)\b/gi, replacement: 'unlikely', strength: 'medium' },
  { pattern: /\b(NO WAY)\b/gi, replacement: 'unlikely', strength: 'medium' },
  { pattern: /\b(IMPOSSIBLE)\b/gi, replacement: 'very difficult', strength: 'medium' },
  { pattern: /\b(UNSTOPPABLE)\b/gi, replacement: 'persistent', strength: 'medium' },
  { pattern: /\b(UNTHINKABLE)\b/gi, replacement: 'unusual', strength: 'medium' },
  { pattern: /\b(UNIMAGINABLE)\b/gi, replacement: 'unusual', strength: 'medium' },
  { pattern: /\b(INCONCEIVABLE)\b/gi, replacement: 'unusual', strength: 'medium' },
  { pattern: /\b(CRIPPLING)\b/gi, replacement: 'significant', strength: 'medium' },
  { pattern: /\b(CRIPPLED)\b/gi, replacement: 'affected', strength: 'medium' },
  { pattern: /\b(PARALYZED)\b/gi, replacement: 'stopped', strength: 'medium' },
  { pattern: /\b(DEBILITATING)\b/gi, replacement: 'significant', strength: 'medium' },
  { pattern: /\b(DEVESTATING)\b/gi, replacement: 'significant', strength: 'medium' },
  { pattern: /\b(CATASTROPHIC)\b/gi, replacement: 'significant', strength: 'medium' },
  { pattern: /\b(CATASTROPHE)\b/gi, replacement: 'significant event', strength: 'medium' },
  // crisis, emergency are too broad - used in professional contexts
  { pattern: /\b(CRITICAL)\b/g, replacement: 'Important', strength: 'medium' },
  { pattern: /\b(critical)\b/gi, replacement: 'important', strength: 'medium' },
  { pattern: /\b(GRIPPING)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(HORRIFYING)\b/gi, replacement: 'concerning', strength: 'medium' },
  { pattern: /\b(HORRIFIC)\b/gi, replacement: 'concerning', strength: 'medium' },
  { pattern: /\b(PETRIFIED)\b/gi, replacement: 'concerned', strength: 'medium' },
  { pattern: /\b(PETRIFYING)\b/gi, replacement: 'concerning', strength: 'medium' },
  { pattern: /\b(TREMENDOUS)\b/g, replacement: 'Significant', strength: 'light' },
  { pattern: /\b(tremendous)\b/gi, replacement: 'significant', strength: 'light' },
  { pattern: /\b(COLOSSAL)\b/gi, replacement: 'large', strength: 'light' },
  { pattern: /\b(GIGANTIC)\b/gi, replacement: 'large', strength: 'light' },
  { pattern: /\b(MASSIVE)\b/g, replacement: 'Large', strength: 'light' },
  { pattern: /\b(massive)\b/gi, replacement: 'large', strength: 'light' },
  { pattern: /\b(HUGE)\b/g, replacement: 'Large', strength: 'light' },
  { pattern: /\b(huge)\b/gi, replacement: 'large', strength: 'light' },
  { pattern: /\b(ENORMOUS)\b/gi, replacement: 'large', strength: 'light' },
  { pattern: /\b(EPIC)\b/g, replacement: 'Notable', strength: 'light' },
  { pattern: /\b(epic)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(LEGENDARY)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(MONUMENTAL)\b/gi, replacement: 'significant', strength: 'light' },
  // historic/historical are normal words, not sensationalist - removed false positive rules
  { pattern: /\b(GROUNDBREAKING)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(REVOLUTIONARY)\b/gi, replacement: 'new', strength: 'light' },
  { pattern: /\b(PARADIGM SHIFT)\b/gi, replacement: 'change', strength: 'light' },
  { pattern: /\b(GAME-CHANGING)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(TURNING POINT)\b/gi, replacement: 'key moment', strength: 'light' },
  { pattern: /\b(WATERSHED)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(TIPPING POINT)\b/gi, replacement: 'critical point', strength: 'medium' },
  { pattern: /\b(POINT OF NO RETURN)\b/gi, replacement: 'critical point', strength: 'medium' },
  { pattern: /\b(NO TURNING BACK)\b/gi, replacement: 'continuing', strength: 'medium' },
  { pattern: /\b(COUNTDOWN)\b/g, replacement: 'Timeline', strength: 'medium' },
  { pattern: /\b(countdown)\b/gi, replacement: 'timeline', strength: 'medium' },
  { pattern: /\b(TICKING CLOCK)\b/gi, replacement: 'timeline', strength: 'medium' },
  { pattern: /\b(RUNNING OUT OF TIME)\b/gi, replacement: 'limited time', strength: 'medium' },
  { pattern: /\b(TIME IS RUNNING OUT)\b/gi, replacement: 'limited time', strength: 'medium' },
  { pattern: /\b(FINAL WARNING)\b/gi, replacement: 'notification', strength: 'medium' },
  { pattern: /\b(LAST CHANCE)\b/gi, replacement: 'opportunity', strength: 'medium' },
  { pattern: /\b(ONLY CHANCE)\b/gi, replacement: 'opportunity', strength: 'medium' },
  { pattern: /\b(DEADLINE)\b/g, replacement: 'Date', strength: 'light' },
  { pattern: /\b(deadline)\b/gi, replacement: 'date', strength: 'light' },
  { pattern: /\b(EXPIRE(S|D)?)\b/gi, replacement: 'end', strength: 'light' },
  { pattern: /\b(EXPIRATION)\b/gi, replacement: 'end date', strength: 'light' },
  { pattern: /\b(ACT NOW)\b/gi, replacement: 'consider', strength: 'medium' },
  { pattern: /\b(ACT FAST)\b/gi, replacement: 'consider', strength: 'medium' },
  { pattern: /\b(HURRY)\b/g, replacement: 'Consider', strength: 'medium' },
  { pattern: /\b(HURRY UP)\b/gi, replacement: 'consider', strength: 'medium' },
  { pattern: /\b(RUSH)\b/g, replacement: 'Move', strength: 'medium' },
  { pattern: /\b(RUSHING)\b/gi, replacement: 'moving', strength: 'medium' },
  { pattern: /\b(DON'T WAIT)\b/gi, replacement: 'consider', strength: 'medium' },
  { pattern: /\b(NO TIME TO LOSE)\b/gi, replacement: 'consider soon', strength: 'medium' },
  { pattern: /\b(NOT A MOMENT TO SPARE)\b/gi, replacement: 'consider', strength: 'medium' },
  { pattern: /\b(EVERY SECOND COUNTS)\b/gi, replacement: 'time matters', strength: 'medium' },
  { pattern: /\b(RACE AGAINST TIME)\b/gi, replacement: 'timeline', strength: 'medium' },
  { pattern: /\b(BATTLE)\b/g, replacement: 'Conflict', strength: 'medium' },
  { pattern: /\b(battle)\b/gi, replacement: 'conflict', strength: 'medium' },
  { pattern: /\b(WAR)\b/g, replacement: 'Conflict', strength: 'medium' },
  { pattern: /\b(war)\b/gi, replacement: 'conflict', strength: 'medium' },
  { pattern: /\b(FIGHT)\b/g, replacement: 'Disagree', strength: 'medium' },
  { pattern: /\b(fight)\b/gi, replacement: 'disagree', strength: 'medium' },
  { pattern: /\b(FIGHTING)\b/gi, replacement: 'conflict', strength: 'medium' },
  { pattern: /\b(CLASH)\b/g, replacement: 'Disagreement', strength: 'medium' },
  { pattern: /\b(clash)\b/gi, replacement: 'disagreement', strength: 'medium' },
  { pattern: /\b(CONFRONTATION)\b/gi, replacement: 'disagreement', strength: 'medium' },
  { pattern: /\b(DISPUTE)\b/g, replacement: 'Disagreement', strength: 'light' },
  { pattern: /\b(dispute)\b/gi, replacement: 'disagreement', strength: 'light' },
  { pattern: /\b(STANDOFF)\b/gi, replacement: 'disagreement', strength: 'medium' },
  { pattern: /\b(SHOWDOWN)\b/gi, replacement: 'meeting', strength: 'medium' },
  { pattern: /\b(FACE-OFF)\b/gi, replacement: 'meeting', strength: 'medium' },
  { pattern: /\b(SHOWDOWN)\b/gi, replacement: 'encounter', strength: 'medium' },
  { pattern: /\b(FIASCO)\b/gi, replacement: 'problem', strength: 'medium' },
  { pattern: /\b(DEBACLE)\b/gi, replacement: 'problem', strength: 'medium' },
  { pattern: /\b(FOWL-UP)\b/gi, replacement: 'error', strength: 'medium' },
  { pattern: /\b(FAILURE)\b/g, replacement: 'Problem', strength: 'medium' },
  { pattern: /\b(failure)\b/gi, replacement: 'problem', strength: 'medium' },
  { pattern: /\b(FAILED)\b/gi, replacement: 'unsuccessful', strength: 'medium' },
  { pattern: /\b(FAIL)\b/g, replacement: 'Not succeed', strength: 'medium' },
  { pattern: /\b(FAILING)\b/gi, replacement: 'struggling', strength: 'medium' },
  { pattern: /\b(BLUNDER)\b/gi, replacement: 'error', strength: 'medium' },
  { pattern: /\b(MISTAKE)\b/g, replacement: 'Error', strength: 'light' },
  { pattern: /\b(mistake)\b/gi, replacement: 'error', strength: 'light' },
  { pattern: /\b(ERROR)\b/g, replacement: 'Issue', strength: 'light' },
  { pattern: /\b(MISHAP)\b/gi, replacement: 'error', strength: 'light' },
  { pattern: /\b(SCREW-UP)\b/gi, replacement: 'error', strength: 'medium' },
  { pattern: /\b(MESS)\b/g, replacement: 'Problem', strength: 'medium' },
  { pattern: /\b(mess)\b/gi, replacement: 'problem', strength: 'medium' },
  { pattern: /\b(MESSY)\b/gi, replacement: 'problematic', strength: 'medium' },
  { pattern: /\b(CHAOS)\b/g, replacement: 'Disorder', strength: 'medium' },
  { pattern: /\b(chaos)\b/gi, replacement: 'disorder', strength: 'medium' },
  { pattern: /\b(CHAOTIC)\b/gi, replacement: 'disordered', strength: 'medium' },
  { pattern: /\b(MAYHEM)\b/gi, replacement: 'disorder', strength: 'medium' },
  { pattern: /\b(TURMOIL)\b/gi, replacement: 'confusion', strength: 'medium' },
  { pattern: /\b(UPHEAVAL)\b/gi, replacement: 'change', strength: 'medium' },
  { pattern: /\b(TUMULT)\b/gi, replacement: 'confusion', strength: 'medium' },
  { pattern: /\b(UNREST)\b/gi, replacement: 'tension', strength: 'medium' },
  { pattern: /\b(VIOLENCE)\b/gi, replacement: 'conflict', strength: 'medium' },
  { pattern: /\b(VIOLENT)\b/gi, replacement: 'aggressive', strength: 'medium' },
  { pattern: /\b(BLOOD)\b/g, replacement: 'Injury', strength: 'medium' },
  { pattern: /\b(BLOODY)\b/gi, replacement: 'injury-related', strength: 'medium' },
  { pattern: /\b(GORE)\b/gi, replacement: 'injury', strength: 'medium' },
  { pattern: /\b(GRAPHIC)\b/g, replacement: 'Detailed', strength: 'medium' },
  { pattern: /\b(graphic)\b/gi, replacement: 'detailed', strength: 'medium' },
  { pattern: /\b(DISTURBING)\b/gi, replacement: 'unusual', strength: 'medium' },
  { pattern: /\b(UNSETTLING)\b/gi, replacement: 'unusual', strength: 'medium' },
  { pattern: /\b(TROUBLING)\b/gi, replacement: 'concerning', strength: 'medium' },
  { pattern: /\b(ALARMING)\b/g, replacement: 'Notable', strength: 'medium' },
  { pattern: /\b(alarming)\b/gi, replacement: 'notable', strength: 'medium' },
  { pattern: /\b(CHILLING)\b/gi, replacement: 'notable', strength: 'medium' },
  { pattern: /\b(SPOOKY)\b/gi, replacement: 'unusual', strength: 'light' },
  { pattern: /\b(EERIE)\b/gi, replacement: 'unusual', strength: 'light' },
  { pattern: /\b(CREEPY)\b/gi, replacement: 'unusual', strength: 'medium' },
  { pattern: /\b(SINISTER)\b/gi, replacement: 'unusual', strength: 'medium' },
  { pattern: /\b(MENACING)\b/gi, replacement: 'threatening', strength: 'medium' },
  { pattern: /\b(THREAT)\b/g, replacement: 'Concern', strength: 'medium' },
  { pattern: /\b(threat)\b/gi, replacement: 'concern', strength: 'medium' },
  { pattern: /\b(THREATENING)\b/gi, replacement: 'concerning', strength: 'medium' },
  { pattern: /\b(MENACE)\b/g, replacement: 'Concern', strength: 'medium' },
  { pattern: /\b(menace)\b/gi, replacement: 'concern', strength: 'medium' },
  { pattern: /\b(PERIL)\b/gi, replacement: 'risk', strength: 'medium' },
  { pattern: /\b(PERILOUS)\b/gi, replacement: 'risky', strength: 'medium' },
  { pattern: /\b(DIRE)\b/gi, replacement: 'significant', strength: 'medium' },
  { pattern: /\b(DIRE STRAITS)\b/gi, replacement: 'difficulty', strength: 'medium' },
  { pattern: /\b(GRIM)\b/gi, replacement: 'concerning', strength: 'medium' },
  { pattern: /\b(BLEAK)\b/gi, replacement: 'challenging', strength: 'medium' },
  { pattern: /\b(DIRE)\b/g, replacement: 'Significant', strength: 'medium' },
  { pattern: /\b(dire)\b/gi, replacement: 'significant', strength: 'medium' },
  { pattern: /\b(SOLEMN)\b/gi, replacement: 'serious', strength: 'light' },
  { pattern: /\b(SOMBER)\b/gi, replacement: 'serious', strength: 'light' },
  { pattern: /\b(GRAVE)\b/g, replacement: 'Serious', strength: 'medium' },
  { pattern: /\b(grave)\b/gi, replacement: 'serious', strength: 'medium' },
  { pattern: /\b(GRAVELY)\b/gi, replacement: 'seriously', strength: 'medium' },
  { pattern: /\b(SERIOUS)\b/g, replacement: 'Significant', strength: 'light' },
  { pattern: /\b(serious)\b/gi, replacement: 'significant', strength: 'light' },
  { pattern: /\b(SEVERE)\b/gi, replacement: 'significant', strength: 'medium' },
  { pattern: /\b(HARSH)\b/gi, replacement: 'strong', strength: 'medium' },
  { pattern: /\b(BRUTAL)\b/gi, replacement: 'strong', strength: 'medium' },
  { pattern: /\b(SAVAGE)\b/gi, replacement: 'strong', strength: 'medium' },
  { pattern: /\b(VICIOUS)\b/gi, replacement: 'aggressive', strength: 'medium' },
  { pattern: /\b(RUTHLESS)\b/gi, replacement: 'determined', strength: 'medium' },
  { pattern: /\b(MERCILESS)\b/gi, replacement: 'determined', strength: 'medium' },
  { pattern: /\b(RELENTLESS)\b/gi, replacement: 'persistent', strength: 'medium' },
  { pattern: /\b(UNFORGIVING)\b/gi, replacement: 'strict', strength: 'medium' },
  // --- Gap-Filling Rules (from stress tests) ---
  // Clickbait patterns
  { pattern: /\b(the real reason (why|for))\b/gi, replacement: 'the reason', strength: 'light' },
  { pattern: /\b(only \d+%? (of )?people (can|know|understand|pass|solve))\b/gi, replacement: 'few people', strength: 'light' },
  { pattern: /\b(i quit my job after (learning|finding|discovering))\b/gi, replacement: 'I changed jobs after learning', strength: 'light' },
  // Ragebait patterns
  { pattern: /\b(literally (tried|attempted|deleted|destroyed))\b/gi, replacement: 'attempted to', strength: 'medium' },
  { pattern: /\b(got caught)\b/gi, replacement: 'was discovered', strength: 'medium' },
  { pattern: /\b(losing their minds)\b/gi, replacement: 'are upset', strength: 'medium' },
  { pattern: /\b(lost their minds)\b/gi, replacement: 'were upset', strength: 'medium' },
  // Manipulative patterns
  { pattern: /\b(government (doesn't|does not) want you to know)\b/gi, replacement: 'government has not widely publicized', strength: 'medium' },
  { pattern: /\b(they (don't|do not) want you to know)\b/gi, replacement: 'may not be widely known', strength: 'medium' },
  { pattern: /\b(everyone is (switching|moving|changing|abandoning))\b/gi, replacement: 'some people are changing', strength: 'light' },
  { pattern: /\b(nobody is talking about)\b/gi, replacement: 'few are discussing', strength: 'light' },
  { pattern: /\b(this changes everything)\b/gi, replacement: 'this is significant', strength: 'light' },
  // More aggressive ALL CAPS patterns
  { pattern: /\b(EXPOSED|REVEALED|CONFIRMED):?\s*/gi, replacement: '', strength: 'light' },
  { pattern: /\b(BREAKING NEWS|BREAKING STORY):?\s*/gi, replacement: '', strength: 'light' },
  // --- Additional patterns from adversarial testing ---
  // Typo/slang variations of "you won't believe"
  { pattern: /\b(u won'?t believe)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(yo won'?t believe)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(yu won'?t believe)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(you wont believe)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(you won'?t beli?e?ve)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(hard to believe)\b/gi, replacement: 'notable', strength: 'light' },
  // Emotional hooks
  { pattern: /\b(will blow your mind)\b/gi, replacement: 'may interest you', strength: 'light' },
  { pattern: /\b(blow your mind)\b/gi, replacement: 'interest you', strength: 'light' },
  { pattern: /\b(will leave you shaking)\b/gi, replacement: 'may affect you', strength: 'medium' },
  { pattern: /\b(will restore your faith)\b/gi, replacement: 'may encourage you', strength: 'light' },
  { pattern: /\b(restore.*faith)\b/gi, replacement: 'encourage', strength: 'light' },
  { pattern: /\b(will break your heart)\b/gi, replacement: 'may concern you', strength: 'medium' },
  { pattern: /\b(break your heart)\b/gi, replacement: 'concern you', strength: 'medium' },
  { pattern: /\b(will shock you)\b/gi, replacement: 'may surprise you', strength: 'light' },
  { pattern: /\b(will make you (cry|laugh|smile))\b/gi, replacement: 'may affect you', strength: 'light' },
  // Urgency patterns
  { pattern: /\b(before they delete (this|it))\b/gi, replacement: '', strength: 'medium' },
  { pattern: /\b(watch before deleted)\b/gi, replacement: 'consider watching', strength: 'medium' },
  { pattern: /\b(must read)\b/gi, replacement: 'worth reading', strength: 'light' },
  { pattern: /\b(limited time)\b/gi, replacement: 'available', strength: 'light' },
  // Curiosity gaps
  { pattern: /\b(what happens next)\b/gi, replacement: 'the outcome', strength: 'light' },
  { pattern: /\b(the reason why)\b/gi, replacement: 'the reason', strength: 'light' },
  { pattern: /\b(here'?s why)\b/gi, replacement: 'the reason', strength: 'light' },
  { pattern: /\b(this is why)\b/gi, replacement: 'the reason', strength: 'light' },
  { pattern: /\b(what (they|nobody) (don'?t|doesn'?t) tell you)\b/gi, replacement: 'what may not be widely known', strength: 'medium' },
  { pattern: /\b(the secret to)\b/gi, replacement: 'a method for', strength: 'light' },
  { pattern: /\b(what happens when)\b/gi, replacement: 'what occurs when', strength: 'light' },
  // Numbers patterns
  { pattern: /\b(top \d+ (things|reasons|secrets|tips|tricks|facts|ways))\b/gi, replacement: 'notable points', strength: 'light' },
  { pattern: /\b(\d+ (things|reasons|secrets|tips|tricks) you)\b/gi, replacement: 'points you', strength: 'light' },
  { pattern: /\b(only \d+%? (of )?people)\b/gi, replacement: 'few people', strength: 'light' },
  { pattern: /\b(\d+%? of people (can|know|understand|pass|solve))\b/gi, replacement: 'some people can', strength: 'light' },
  // Simpler number patterns for standalone phrases
  { pattern: /\b(top \d+)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(\d+ things)\b/gi, replacement: 'several things', strength: 'light' },
  { pattern: /\b(\d+ reasons)\b/gi, replacement: 'several reasons', strength: 'light' },
  { pattern: /\b(\d+ secrets)\b/gi, replacement: 'several points', strength: 'light' },
  { pattern: /\b(\d+ signs)\b/gi, replacement: 'several signs', strength: 'light' },
  { pattern: /\b(number one)\b/gi, replacement: 'primary', strength: 'light' },
  // Authority patterns
  { pattern: /\b(scientists discovered)\b/gi, replacement: 'researchers found', strength: 'light' },
  { pattern: /\b(experts reveal)\b/gi, replacement: 'experts note', strength: 'light' },
  { pattern: /\b(studies show)\b/gi, replacement: 'studies suggest', strength: 'light' },
  { pattern: /\b(research proves)\b/gi, replacement: 'research indicates', strength: 'light' },
  { pattern: /\b(what big pharma)\b/gi, replacement: 'what pharmaceutical companies', strength: 'medium' },
  { pattern: /\b(what the media)\b/gi, replacement: 'what news outlets', strength: 'medium' },
  // More ragebait
  { pattern: /\b(instant karma)\b/gi, replacement: 'consequences', strength: 'medium' },
  { pattern: /\b(karma)\b/gi, replacement: 'result', strength: 'medium' },
  { pattern: /\b(entitled (customer|person|people))\b/gi, replacement: 'assertive person', strength: 'medium' },
  // Superlatives
  { pattern: /\b(jaw-dropping)\b/gi, replacement: 'notable', strength: 'light' },
  { pattern: /\b(earth-shattering)\b/gi, replacement: 'significant', strength: 'light' },
  { pattern: /\b(mind-blowing)\b/gi, replacement: 'interesting', strength: 'light' },
  { pattern: /\b(heartbreaking)\b/gi, replacement: 'concerning', strength: 'medium' },
  { pattern: /\b(devastating)\b/gi, replacement: 'significant', strength: 'medium' },
  { pattern: /\b(life-changing)\b/gi, replacement: 'notable', strength: 'light' },
  // --- Exclusivity patterns (clickbait context) ---
  { pattern: /\b(something (exclusive|secret|hidden|classified))\b/gi, replacement: 'something special', strength: 'light' },
  { pattern: /\b(exclusive (access|offer|deal|content|report|story|video))\b/gi, replacement: 'special', strength: 'light' },
  { pattern: /\b(exclusive[:\s]+(report|news|video|story|content))\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(for (a )?limited time( only)?)\b/gi, replacement: 'temporarily', strength: 'light' },
  { pattern: /\b(limited (time|edition|availability) (offer|deal|access|content)?)\b/gi, replacement: 'available', strength: 'light' },
  { pattern: /\b(rare (opportunity|chance|find|footage))\b/gi, replacement: 'special', strength: 'light' },
  { pattern: /\b(a rare (opportunity|chance|find))\b/gi, replacement: 'an opportunity', strength: 'light' },
  { pattern: /\b(classified (documents|files|information|footage|leaks?))\b/gi, replacement: 'restricted', strength: 'medium' },
  { pattern: /\b(insiders? (only|access|information|report))\b/gi, replacement: 'exclusive', strength: 'light' },
  { pattern: /\b(members? (only|access|exclusive))\b/gi, replacement: 'subscriber', strength: 'light' },
  { pattern: /\b(not (for )?public (release|viewing|access))\b/gi, replacement: 'restricted', strength: 'medium' },
  // --- Urgency patterns ---
  { pattern: /\b(watch (this|before) (it (gets|is) )?(deleted|removed|banned))\b/gi, replacement: 'consider watching', strength: 'medium' },
  { pattern: /\b(before it (gets|is) (deleted|removed|banned))\b/gi, replacement: '', strength: 'medium' },
  // --- Disaster/scandal patterns ---
  { pattern: /\b(disaster strikes[:\s]*)\b/gi, replacement: '', strength: 'medium' },
  { pattern: /\b(scandal (erupts|grows|widens))\b/gi, replacement: 'situation develops', strength: 'medium' },
  // --- "Literally" with emotion (ragebait) ---
  { pattern: /\b(literally (sick|shaking|crying|screaming|dying|fuming))\b/gi, replacement: 'very', strength: 'medium' },
  // --- "Secret move" pattern ---
  { pattern: /\b(in (a )?secret (move|deal|agreement))\b/gi, replacement: 'in a private', strength: 'medium' },
  // --- Bandwagon patterns ---
  { pattern: /\b(everyone (is |are )(talking about|discussing))\b/gi, replacement: 'people are discussing', strength: 'light' },
  { pattern: /\b(everyone'?s talking about)\b/gi, replacement: 'people are discussing', strength: 'light' },
  { pattern: /\b(everyone knows?)\b/gi, replacement: 'it is known', strength: 'light' },
  { pattern: /\b(everyone (needs?|should|must) (to )?(know|see|watch|read))\b/gi, replacement: 'you may want to', strength: 'light' },
  { pattern: /\b(just in:)\b/gi, replacement: '', strength: 'light' },
  { pattern: /\b(JUST IN:)\b/g, replacement: '', strength: 'light' },
  { pattern: /\b(the only (way|method|solution|answer|option) (to|for))\b/gi, replacement: 'a way to', strength: 'light' },
  { pattern: /\b(going viral)\b/gi, replacement: 'becoming popular', strength: 'light' },
  // --- Conspiracy patterns ---
  { pattern: /\b(what (they're|they are|they) hiding)\b/gi, replacement: 'undisclosed information', strength: 'medium' },
  { pattern: /\b(the truth (they|the government|they) hide)\b/gi, replacement: 'the information not shared', strength: 'medium' },
  { pattern: /\b(mainstream media won'?t tell)\b/gi, replacement: 'news outlets may not share', strength: 'medium' },
  { pattern: /\b(big pharma (doesn'?t|does not) want)\b/gi, replacement: 'pharmaceutical companies may not share', strength: 'medium' },
  { pattern: /\b(what('?s| is) really going on)\b/gi, replacement: 'what is happening', strength: 'medium' },
  { pattern: /\b(wake up(!?| sheeple!?))\b/gi, replacement: 'consider', strength: 'medium' },
  { pattern: /\b(sheeple)\b/gi, replacement: 'people', strength: 'medium' },
  { pattern: /\b(do your own research)\b/gi, replacement: 'research further', strength: 'light' },
  { pattern: /\b(follow the money)\b/gi, replacement: 'consider the financial aspects', strength: 'light' },
];

const STRENGTH_PRIORITY: Record<RewriteMode, string[]> = {
  light: ['light'],
  medium: ['light', 'medium'],
  strict: ['light', 'medium', 'strict'],
};

function cleanText(text: string): string {
  return text
    .replace(/\s+/g, ' ')
    .replace(/\s+([.,!?;:])/g, '$1')
    .replace(/([.,!?;:])\s+/g, '$1 ')
    .trim();
}

function preserveCase(original: string, replacement: string): string {
  if (!original || !replacement) return replacement;
  
  if (original[0] === original[0].toUpperCase()) {
    return replacement.charAt(0).toUpperCase() + replacement.slice(1);
  }
  return replacement.toLowerCase();
}

export function rewriteWithLocalRules(
  text: string,
  options: { mode: RewriteMode }
): RewriteResult {
  let rewritten = text;
  const changes: TextChange[] = [];
  const allowedStrengths = STRENGTH_PRIORITY[options.mode];

  for (const rule of NEUTRALIZATION_RULES) {
    if (!allowedStrengths.includes(rule.strength)) continue;

    const matches = text.match(rule.pattern);
    if (matches) {
      for (const originalMatch of matches) {
        const replacement = rule.preserveCapitalization !== false
          ? preserveCase(originalMatch, rule.replacement)
          : rule.replacement;

        rewritten = rewritten.replace(originalMatch, replacement);
        
        if (originalMatch !== replacement) {
          changes.push({
            original: originalMatch,
            replacement: replacement,
            reason: `neutralization_rule:${rule.strength}`,
          });
        }
      }
    }
  }

  rewritten = cleanText(rewritten);

  const confidence = changes.length > 0 
    ? Math.min(1, 0.5 + (changes.length * 0.1))
    : 1.0;

  return {
    original: text,
    rewritten,
    changes,
    confidence,
    mode: options.mode,
  };
}

export function getRulesForMode(mode: RewriteMode): NeutralizationRule[] {
  const allowedStrengths = STRENGTH_PRIORITY[mode];
  return NEUTRALIZATION_RULES.filter(rule => allowedStrengths.includes(rule.strength));
}

export function previewChanges(text: string, mode: RewriteMode): TextChange[] {
  const result = rewriteWithLocalRules(text, { mode });
  return result.changes;
}